export const SUPPORTED_LANGUAGES = ["en", "ru"];

const messages = {
  en: {
    appName: "Browser Monitor",
    extensionEnabled: "Extension enabled",
    extensionPaused: "Browser Monitor is paused",
    settings: "Settings",
    language: "Language",
    english: "English",
    russian: "Русский",
    navAnalytics: "Analytics",
    navGeneral: "General",
    navFilters: "Filters",
    navPageElements: "Page elements",
    navLinkSafety: "Link safety",
    navHistoryPrivacy: "History filter",
    navProtectionCenter: "Protection",
    navPrivacyTools: "Privacy",
    navProtection: "Protection",
    navComfort: "Comfort",
    navAppearance: "Appearance",
    navRules: "Advanced rules",
    navData: "Data",
    navFeedback: "Feedback",
    heroEyebrow: "Browser protection, without the noise",
    heroTitle: "Your browser, calmer and lighter.",
    heroDescription: "Block ads and trackers, remove interruptions, and understand what slows down every tab. Everything is processed locally.",
    settingsTitle: "Settings",
    settingsDescription: "Manage extension behavior, page tools, and local data.",
    protectionOn: "Protection is on",
    protectionOff: "Protection is off",
    activeRules: "active network rules",
    statusDescription: "Main browser protection status",
    sectionGeneral: "General",
    sectionGeneralDescription: "Main protection and tab-analysis switches.",
    sectionFilters: "Filters",
    sectionFiltersDescription: "Choose the network and page filter lists used by the extension.",
    sectionProtectionCenter: "Protection",
    sectionProtectionCenterDescription: "Choose what Browser Monitor blocks, hides, or cleans up while pages load.",
    filterListsGroup: "Network and list filters",
    filterListsGroupDescription: "Core blocking rules that stop ads, trackers, cryptominers, and regional advertising resources.",
    sectionPageElements: "Page elements",
    sectionPageElementsDescription: "Control cookie banners, pop-ups, prompts, autoplay, and floating video.",
    pageCleanupGroup: "Page cleanup",
    pageCleanupGroupDescription: "Optional controls for overlays, prompts, video interruptions, and sponsored segments.",
    sectionLinkSafety: "Link safety",
    sectionLinkSafetyDescription: "Warn before opening links with phishing-style or suspicious destination signals.",
    sectionHistoryPrivacy: "History filter",
    sectionHistoryPrivacyDescription: "Keep selected domains out of local Chrome history and hide matching search suggestions on supported search pages.",
    sectionPrivacyTools: "Privacy",
    sectionPrivacyToolsDescription: "Manage suspicious-link warnings, blocked destinations, and local history cleanup in one place.",
    securityGroup: "Security",
    securityGroupDescription: "Manage copy protection, video resume, search labels, and suspicious-link warnings.",
    automaticProtectionGroup: "Automatic local protection",
    automaticProtectionGroupDescription: "Quiet safeguards that work without accounts, cloud checks, or additional switches.",
    alwaysOn: "Always on",
    localOnlyBadge: "Local",
    sectionAnalytics: "Tab analytics",
    sectionAnalyticsDescription: "See which open pages are working hardest, why they are heavy, and whether pausing them will help. Measurements stay inside this browser profile.",
    refreshAnalytics: "Refresh analysis",
    analyticsUpdated: "Updated {time}",
    openTabsStat: "Open tabs",
    openTabsStatDescription: "Regular web pages available for local analysis.",
    attentionStat: "Need attention",
    attentionStatDescription: "Heavy or critical tabs worth reviewing.",
    activityHistory: "Recent activity",
    activityHistoryDescription: "Daily peak tab load and blocked requests. Only compact totals are kept for 90 days.",
    lastSevenDays: "7 days",
    tabLoad: "Current tab load",
    tabLoadDescription: "Scores combine main-thread blocking, layout work, network volume, media, and background activity.",
    noAnalyzedTabs: "No regular web tabs are available yet. Open a website or enable tab analysis.",
    openTab: "Open tab",
    scoreLabel: "Load score",
    historyBlocked: "{count} blocked",
    historyScore: "peak {score}",
    sectionProtection: "Protection",
    sectionProtectionDescription: "Choose what Chrome blocks before a page loads. Declarative rules run inside Chrome and do not inspect every request in JavaScript.",
    masterProtection: "Block ads and trackers",
    masterProtectionDescription: "Blocks advertising and tracking requests and removes supported page interruptions.",
    tabAnalysis: "Analyze tab activity",
    tabAnalysisDescription: "Finds tabs that use the most processor, network, media, or background time.",
    easyList: "Advertising filters",
    easyListDescription: "Blocks common advertising requests and page elements.",
    easyPrivacy: "Tracking protection",
    easyPrivacyDescription: "Blocks known analytics and advertising trackers.",
    crypto: "Cryptomining protection",
    cryptoDescription: "Stops known browser-mining scripts.",
    cosmetic: "Clean empty ad spaces",
    cosmeticDescription: "Hides empty containers left after ads are blocked.",
    russianFilters: "Russian-language page filters",
    russianFiltersDescription: "Adds RU AdList rules for Russian-language sites.",
    socialFilters: "Tracking social widgets",
    socialFiltersDescription: "Hides social widgets that track visits.",
    warningFilters: "Ad-block warning messages",
    warningFiltersDescription: "Hides common requests to disable ad blocking.",
    sectionComfort: "Comfort",
    sectionComfortDescription: "Optional controls for the things that interrupt reading. These are off until you choose to enable them.",
    cookieBanners: "Cookie consent banners",
    cookieBannersDescription: "Hides supported cookie-consent overlays.",
    newsletters: "Newsletter pop-ups",
    newslettersDescription: "Removes common e-mail subscription dialogs that cover page content.",
    surveys: "Survey requests",
    surveysDescription: "Hides common survey dialogs and feedback overlays.",
    notificationPrompts: "Notification prompts",
    notificationPromptsDescription: "Hides website prompts asking to enable notifications.",
    autoplay: "Unsolicited autoplay",
    autoplayDescription: "Pauses autoplaying audio and video until you interact with the page.",
    floatingVideo: "Floating and sticky video",
    floatingVideoDescription: "Hides video players that follow the page while you scroll.",
    videoAdProtection: "Video-player ads",
    videoAdProtectionDescription: "Blocks recognized advertising inside supported video players.",
    sponsorSkipping: "Sponsored integrations",
    sponsorSkippingDescription: "Skips SponsorBlock community segments on YouTube.",
    searchProtection: "Search result protection",
    searchProtectionDescription: "Shows trust marks and warnings beside supported search results.",
    linkSafetyEnabled: "Suspicious link warnings",
    linkSafetyEnabledDescription: "Open a Browser Monitor warning page before visiting links that look risky.",
    warnShorteners: "Shortened links",
    warnShortenersDescription: "Warn when the destination is hidden behind common URL shorteners.",
    warnLookalikes: "Lookalike domains",
    warnLookalikesDescription: "Warn when a hostname imitates a known brand but the real domain is different.",
    warnPunycode: "Punycode and mixed alphabets",
    warnPunycodeDescription: "Warn about domains that may hide confusing characters.",
    warnRedirects: "Nested redirects",
    warnRedirectsDescription: "Warn when URL parameters contain another destination URL.",
    warnUnknownFromSocial: "Social-feed links",
    warnUnknownFromSocialDescription: "Raise warnings for risky links leaving social sites such as X, Reddit, or Telegram Web.",
    linkSafetyAllowedDomains: "Allowed domains",
    linkSafetyAllowedDomainsDescription: "Never warn for these domains or subdomains. Enter one address per line.",
    linkSafetyBlockedDomains: "Blocked domains",
    linkSafetyBlockedDomainsDescription: "Always show the warning page for these registrable domains.",
    domainListsTitle: "Domain lists",
    domainListsDescription: "Manage destinations that are always trusted or always blocked.",
    domainListsDialogDescription: "Add one domain or subdomain per line.",
    builtInTrustedDomains: "{count} official service domains are already recognized; add only personal exceptions here.",
    close: "Close",
    cancel: "Cancel",
    saveLinkSafety: "Save link safety",
    historyPrivacyEnabled: "Hide selected domains from history",
    historyPrivacyEnabledDescription: "When enabled, Browser Monitor removes matching local Chrome history entries after direct user permission.",
    historyPrivacyDomains: "Domains to hide",
    historyPrivacyDomainsDescription: "One registrable domain per line, for example youtube.com. Search suggestions containing these names are hidden on Google, Yandex, and Bing pages.",
    saveHistoryPrivacy: "Save history filter",
    purgeHistoryPrivacy: "Clean matching history now",
    cryptoGuardTitle: "Crypto Guard",
    cryptoGuardDescription: "Detects a substituted blockchain address during copy and paste.",
    continueWatchingTitle: "Continue watching",
    continueWatchingDescription: "Restores saved positions in recognized long-form videos.",
    sectionAppearance: "Appearance",
    sectionAppearanceDescription: "Configure Image Swap and the interface theme.",
    imageSwap: "Image Swap",
    imageSwapDescription: "Replaces suitable blocked ad spaces with selected artwork.",
    imageCollection: "Artwork collection",
    landscape: "Landscape",
    ocean: "Ocean",
    minimal: "Minimal",
    custom: "My images",
    customImages: "Your local images",
    customImagesDescription: "Add up to nine JPG, PNG, WebP, GIF, or BMP images. Each file must be under 1 MB, with a 6 MB total, and never leaves this browser profile.",
    chooseImages: "Choose images",
    removeImages: "Remove all",
    noCustomImages: "No custom images added",
    imageCount: "{count} local image(s)",
    interfaceTheme: "Extension theme",
    interfaceThemeDescription: "Changes the extension interface color scheme.",
    themeSystem: "System",
    themeLight: "Light",
    themeDark: "Dark",
    themeSolarized: "Solarized",
    themeForest: "Forest",
    sectionRules: "Advanced rules",
    sectionRulesDescription: "Manage site exceptions, blocked request domains, hidden elements, and HTTPS filter-list subscriptions.",
    siteExceptions: "Site exceptions",
    siteExceptionsDescription: "Protection stays off on these domains. Enter one domain per line, for example example.com.",
    blockedDomains: "Blocked domains",
    blockedDomainsDescription: "Always block requests to these domains. Up to 1,000 entries.",
    cosmeticRules: "Hidden page elements",
    cosmeticRulesDescription: "CSS selectors created by the element picker or entered manually. Invalid selectors are ignored.",
    filterSubscriptions: "Filter-list subscriptions",
    filterSubscriptionsDescription: "Add up to two direct HTTPS filter-list URLs. Unsafe allow, redirect, scriptlet, and unsupported rules are rejected.",
    saveRules: "Save rules",
    updateLists: "Update lists now",
    updated: "Updated {time}",
    updateFailed: "Update failed: {error}",
    ruleSummary: "{network} network · {cosmetic} page rules",
    sectionData: "Data and privacy",
    sectionDataDescription: "Manage retention, tool behavior, backups, and diagnostics.",
    localOnly: "Local by design",
    localOnlyDescription: "Settings, tab analytics, and rule diagnostics stay on this Mac. Browser Monitor has no analytics server or account.",
    backup: "Backup and restore",
    backupDescription: "Export extension settings or restore a previous backup.",
    exportSettings: "Export settings",
    importSettings: "Import settings",
    resetSettings: "Restore defaults",
    activityLauncherTitle: "Site activity · NEW",
    activityLauncherDescription: "Active time, reading and video",
    activityHint: "Open site activity analytics",
    feedbackButton: "Feedback",
    feedbackHint: "Suggest a tool or report a problem",
    sectionFeedback: "Feedback",
    sectionFeedbackDescription: "Suggest a new tool or report a problem. Requests are reviewed before they are submitted.",
    feedbackCardTitle: "Help improve Browser Monitor",
    feedbackCardDescription: "Open a short form with your email, request details, and an optional screenshot.",
    contactIntro: "You can also contact the developer directly.",
    openFeedback: "Open feedback form",
    backupReady: "Settings backup downloaded.",
    importReady: "Settings restored. Open pages may need to be reloaded.",
    invalidBackup: "This backup file is invalid or unsupported.",
    resetConfirm: "Restore all protection settings to their defaults? Site exceptions and custom rules will be removed.",
    importConfirm: "Replace current protection settings and exceptions with this backup?",
    saved: "Saved",
    saving: "Saving…",
    error: "Could not save changes.",
    openSettings: "Open settings",
    collecting: "Collecting data…",
    dataUnavailable: "Data is temporarily unavailable",
    dataTemporarilyUnavailable: "Showing the latest available data",
    refreshToRetry: "Refresh to try again",
    analysisPaused: "Tab analysis is paused",
    tabsSummary: "{tabs} · {attention}",
    tabsCountOne: "1 tab",
    tabsCountMany: "{count} tabs",
    attentionOne: "1 needs attention",
    attentionMany: "{count} need attention",
    appConnected: "App connected",
    extensionOnly: "Extension only",
    currentSite: "Current site",
    checkingAddress: "Checking address…",
    excludeSite: "Exclude site",
    protectSite: "Protect site",
    reportSite: "Report a filter problem on this site",
    allowedHere: "Ads and trackers are allowed here",
    protectionActiveHere: "Ads and trackers are blocked on this site",
    pausedUntil: "Paused until {time}",
    pause10: "Pause 10 min",
    cleanupSiteDataHint: "Clear sign-in data when the last tab for this site closes",
    cleanupSiteDataEnabled: "Site data will be cleared after its last tab closes.",
    cleanupSiteDataDisabled: "Automatic site-data cleanup is off for this site.",
    cleanupPermissionDenied: "Chrome permission is required to clear site data.",
    resume: "Resume",
    resumeProtection: "Resume protection",
    sitePausedNotice: "Protection is paused on this site for 10 minutes. Press the pause icon again to resume now.",
    siteProtectionResumed: "Protection has resumed on this site.",
    privacyReceipt: "Site privacy receipt",
    privacyReceiptHint: "Show a local privacy receipt for this site",
    receiptBlocked: "DNR + guards",
    receiptThirdParty: "network requests",
    receiptCookies: "page-visible cookies",
    receiptStorage: "page storage keys",
    receiptLocalOnly: "Kept locally only for this visit.",
    receiptProtected: "Protected",
    receiptPaused: "Paused",
    receiptCollecting: "Collecting…",
    receiptObserved: "{duration} observed",
    receiptDomains: "{count} domains · {requests} requests: {domains}",
    receiptNoDomains: "No third parties spotted so far.",
    receiptDetailsButton: "See details",
    receiptDetailsTitle: "Site Privacy Details",
    receiptAllowedRequests: "Allowed",
    receiptBlockedRequests: "Blocked",
    receiptUnknownRequests: "Other failures",
    receiptNetworkSource: "Observed network requests",
    receiptProtectionSource: "DNR and Browser Monitor guards",
    receiptUnknownSource: "Cancelled, failed or not classified",
    receiptCategoryNote: "Domain purposes are local filename heuristics, not verified ownership.",
    receiptCategoryAds: "Ads",
    receiptCategoryAnalytics: "Analytics",
    receiptCategoryVideo: "Video",
    receiptCategorySocial: "Social",
    receiptCategoryCdn: "CDN",
    receiptCategoryOther: "Other",
    blockedResources: "Blocked Trackers & Resources",
    thirdPartyConnections: "Third-Party Connections",
    noBlockedResources: "No resources blocked.",
    noThirdPartyConnections: "No third-party connections.",
    exceptions: "Exceptions",
    remove: "Remove",
    tabActivity: "Tab activity",
    tools: "Tools",
    previousTools: "Previous tools",
    nextTools: "Next tools",
    watchHistoryButton: "Video",
    siteResetButton: "Reset",
    siteResetHint: "Choose what to remove now or after the current tab closes",
    siteResetTitle: "Site Reset",
    siteResetWarning: "You may be signed out and unsaved offline data may be lost.",
    siteResetCategories: "Data to remove",
    siteResetCookies: "Cookies",
    siteResetCookiesDetail: "Sign-in and preference cookies",
    siteResetStorage: "Site storage",
    siteResetCache: "Cache",
    siteResetWorkersDetail: "Background site workers",
    siteResetWhen: "When to remove",
    siteResetNow: "Now",
    siteResetOnClose: "After this tab closes",
    siteResetAfter5: "5 min after tab closes",
    siteResetAfter30: "30 min after tab closes",
    siteResetAfter60: "1 hour after tab closes",
    siteResetCloseNote: "Reloading does not start the timer. The countdown begins only when this tab is closed.",
    siteResetApply: "Schedule reset",
    siteResetChooseCategory: "Choose at least one data category.",
    siteResetConfirmNow: "Remove the selected data for {site} now? This cannot be undone.",
    siteResetConfirmSchedule: "Schedule the selected data removal for {site}?",
    siteResetDone: "Selected site data was removed.",
    siteResetScheduled: "Reset scheduled. Reloading will not start it.",
    siteResetFailed: "The site reset could not be completed.",
    reviewButton: "Review",
    reviewHint: "Review old tabs and bookmark structure in one place",
    reviewTitle: "Browser review",
    reviewDescription: "Old tabs and bookmark structure",
    reviewTabs: "Tabs",
    reviewBookmarks: "Bookmarks",
    staleInactiveFor: "Inactive for",
    stale1Day: "1 day",
    stale7Days: "7 days",
    stale30Days: "30 days",
    staleNote: "Pinned and active tabs are excluded.",
    staleEmpty: "No old inactive tabs match this period.",
    staleDays: "{count}d inactive",
    selectAll: "Select all",
    closeSelected: "Close selected",
    closeStaleConfirm: "Close {count} selected tabs?",
    staleClosed: "Closed {count} tabs.",
    bookmarkReviewNote: "Finds malformed and duplicate destinations locally. Bookmarked sites are not contacted.",
    scanBookmarks: "Allow access and scan",
    scanBookmarksAgain: "Scan bookmarks",
    bookmarksPermissionPrompt: "Browser Monitor needs Bookmarks access only to inspect bookmark titles and destinations locally.",
    bookmarkStartScan: "Run the scan to review bookmark structure.",
    bookmarkNoIssues: "No structural issues found.",
    bookmarkHealthy: "Checked {count} bookmarks. No structural issues found.",
    bookmarkIssuesFound: "Found {count} items to review.",
    bookmarkDuplicate: "Duplicate destination",
    bookmarkInvalid: "Malformed address",
    bookmarkScanFailed: "Bookmarks could not be read. Try again.",
    back: "Back",
    duplicateTabsButton: "Duplicates",
    duplicateTabsHint: "Find duplicate tabs",
    duplicateTabsTitle: "Duplicate tabs",
    duplicateTabsDescription: "Matching pages with tracking fragments ignored",
    closeDuplicateTabs: "Close duplicates",
    noDuplicateTabs: "No duplicate tabs found.",
    duplicateCopies: "{count} matching tabs",
    watchHistoryHint: "Show recently watched videos",
    watchHistoryTitle: "Recently watched",
    closeWatchHistory: "Close recently watched",
    watchHistoryLoading: "Loading recent videos…",
    watchHistoryEmpty: "Films, episodes, and long videos you pause will appear here.",
    watchHistoryUntitled: "Untitled video",
    watchHistoryEpisode: "Episode",
    watchHistoryMovie: "Film",
    watchHistoryVideo: "Video",
    watchHistoryOpen: "Open on {site}",
    statisticsButton: "Stats",
    statisticsHint: "Open blocking statistics",
    statisticsTitle: "Blocking activity",
    statisticsDescription: "A private, local view of Browser Monitor protection.",
    liveUpdates: "Live updates",
    blockedToday: "Blocked today",
    blockedSevenDays: "Last 7 days",
    rollingWindow: "Rolling local window",
    networkRequests: "Network",
    videoAndSponsors: "Video + sponsors",
    sevenDayActivity: "Seven-day activity",
    sevenDayActivityDescription: "Blocked requests and recognized video interruptions.",
    topBlockedSites: "Top sites",
    topBlockedSitesDescription: "Pages where protection was most active.",
    blockedResources: "Blocked resources",
    blockedResourcesDescription: "Domains and video categories stopped by protection.",
    noBlockingActivity: "No blocking activity yet.",
    noBlockedResources: "Blocked resources will appear here.",
    statisticsPrivacy: "Only seven days of compact counters are kept locally. Full page URLs are not stored; SponsorBlock results may cache a YouTube video ID for up to 12 hours.",
    clearStatistics: "Clear statistics",
    clearStatisticsConfirm: "Clear all locally stored blocking statistics?",
    statisticsBreakdown: "{network} network · {video} video · {sponsor} sponsors",
    waitingForBlocks: "Waiting for activity",
    cookies: "Cookies",
    cookieToolHint: "View and export current-site cookies after granting Chrome access",
    blockElement: "Block",
    refresh: "Refresh",
    tabDetails: "Tab details",
    whyItMatters: "Why it matters",
    recommendation: "Recommendation",
    export: "Export",
    saveAs: "Save As",
    copy: "Copy",
    exportAllCookies: "Export all browser cookies",
    exportFormat: "Export format",
    cookieDomain: "Domain",
    cookieIdentity: "Cookie",
    cookieProtection: "Protection",
    cookieUnnamed: "Unnamed",
    cookieValueHidden: "Value hidden in Browser Monitor",
    cookieRevealValue: "Reveal this cookie value",
    cookieHideValue: "Hide this cookie value",
    cookieEmptyValue: "This cookie has an empty value",
    cookieSecure: "Sent over secure connections",
    cookieHttpOnly: "Hidden from page scripts",
    cookieNoProtectionFlags: "No Secure or HttpOnly flag",
    cookieSession: "Session",
    cookiePersistent: "Persistent",
    cookieSessionHint: "Removed when the browser session ends",
    cookieExpires: "Expires {date}",
    cookieSameSiteMissing: "No SameSite",
    cookieSameSiteHint: "Cookie cross-site policy reported by Chrome",
    cookiePartitioned: "Partitioned",
    cookiePartitionedHint: "Stored in a partitioned cookie jar",
    cookieScriptAccessible: "Accessible to page JavaScript because HttpOnly is absent",
    cookieScriptAccessibleShort: "Script access",
    cookieLongLived: "400d+",
    cookieLongLivedHint: "Expiration is more than 400 days away",
    cookieAdvanced: "Advanced browser-wide export",
    cookieAdvancedWarning: "Includes sign-in cookies from every site. Use only for a deliberate backup.",
    storageMapTitle: "Site Storage Map",
    storageMapSource: "Page inspection · approximate origin usage",
    storageQuota: "Quota",
    cookieChangesTitle: "Changes during this browser session",
    cookieChangesEmpty: "No cookie changes observed for this site yet.",
    cookieChangeCreated: "Created",
    cookieChangeUpdated: "Updated",
    cookieChangeRemoved: "Removed",
    cookieHistoryOpen: "Open cookie history and browser-wide export",
    cookieHistoryTitle: "Cookie history",
    cookieHistoryDescription: "Value-free changes observed during this browser session.",
    cookieHistoryPrivacy: "Values are never stored in this history.",
    cookieHistoryTime: "Time",
    cookieHistoryEvent: "Event",
    cookieHistoryEmpty: "No cookie changes have been observed in this browser session.",
    cookieHistorySessionNote: "History is kept locally for up to 12 hours and is cleared with the browser session.",
    cookieBrowserScope: "Browser-wide",
    cookieBrowserExportTitle: "Export all cookies",
    cookieBrowserExportDescription: "Creates one local backup containing cookies from every browser site.",
    cookieAccessTitle: "Cookie access required",
    cookieAccessDescription: "Grant access to begin recording value-free cookie changes and enable browser-wide export.",
    cookieGrantAccess: "Grant access",
    noCookies: "No cookies found for this site.",
    cookieWarning: "Cookie files can grant account access. Keep exports private.",
    settingsHint: "All protection controls and explanations",
    openRegularPage: "Open a regular webpage to see its activity.",
    turnAnalysisOn: "Turn analysis on to monitor tab load.",
    untitled: "Untitled",
    noSignificantLoad: "No significant load sources detected",
    pauseTab: "Pause",
    resumeTab: "Resume",
    restoreTabActivity: "Restore normal tab activity",
    pauseTabActivity: "Pause media, animations, and background network activity",
    activeTab: "Active tab",
    backgroundTab: "Background tab",
    recentlyBackground: "Recently backgrounded",
    backgroundFor: "Background for {duration}",
    visibleTab: "Visible tab",
    noActionNeeded: "No action is needed right now.",
    metricLongFrames: "Long frames",
    metricBlocking: "Blocking",
    metricLayout: "Layout",
    metricResources: "Resources",
    metricTransferred: "Transferred",
    metricBackground: "Background",
    metricMedia: "Media",
    metricSample: "Sample",
    measurementFull: "full measurement",
    measurementPartial: "partial measurement",
    measurementUnavailable: "measurement unavailable",
    durationSeconds: "{count} sec",
    durationMinutes: "{count} min",
    pauseThisTab: "Pause this tab",
    resumeNormalTab: "Resume normal tab activity",
    internalUnavailable: "Unavailable on Chrome internal pages",
    pictureInPictureActive: "Picture-in-Picture is active",
    noVideoFound: "No video found in the current tab",
    videoFoundOne: "1 video element found",
    videoFoundMany: "{count} video elements found",
    reloadAfterInstall: "Reload the page after installing the extension",
    openingPiP: "Opening Picture-in-Picture…",
    readingCookies: "Reading cookies locally…",
    preparingExport: "Preparing export…",
    preparingCopy: "Preparing a private copy…",
    cookiesCopied: "{count} cookies copied. Paste only into a trusted destination.",
    cookiesExported: "{count} cookies exported to {filename}",
    cookieExportFailed: "Cookie export failed",
    permissionRequired: "Permission was not granted. You can try again when you need this tool.",
    permissionCancelled: "Permission request cancelled.",
    cookiesPermissionPrompt: "Browser Monitor needs Chrome cookie access to inspect cookies for the current site. Values stay on this device. Continue?",
    downloadsPermissionPrompt: "Browser Monitor needs download access only to save the requested export file. Continue?",
    clipboardWritePermissionPrompt: "Browser Monitor needs clipboard access only to copy this export after your action. Continue?",
    browsingDataPermissionPrompt: "Browser Monitor needs browsing-data access to remove this site's cookies and storage after its last tab closes. Continue?",
    historyPermissionPrompt: "Browser Monitor needs history access to remove visits for only the domains you add. History content is not sent anywhere. Continue?",
    settingsDownloadPermissionPrompt: "Browser Monitor needs download access only to save this local settings backup. Continue?",
    exportAllConfirm: "Export every browser cookie? This file may provide access to signed-in accounts. Store it securely and never share it.",
    filtersCount: "{network} + {cosmetic} filters",
    reasonLongBlocks: "Long main-thread blocks",
    reasonLayout: "Frequent style and layout recalculation",
    reasonLayoutShift: "Visible layout instability",
    reasonNetwork: "High network resource volume",
    reasonResourceCount: "Large number of page resources",
    reasonBackground: "Activity continues in the background",
    reasonMedia: "Active media elements on the page",
    recommendationNormal: "This tab can remain open.",
    recommendationNoticeable: "Keep an eye on this tab, especially in the background.",
    recommendationHeavy: "Pause media or reload this tab.",
    recommendationCritical: "Close this tab if you do not need it right now.",
    severityNormal: "normal",
    severityNoticeable: "noticeable",
    severityHeavy: "heavy",
    severityCritical: "critical",
    metricRecent: "Last 60 seconds", metricTotal: "Since opening", backgroundTimeline: "Background activity timeline", backgroundTimelineEmpty: "No background events in the last 60 seconds.",
    "timeline_request": "request", "timeline_long-frame": "long frame", "timeline_layout-shift": "layout shift",
    ecoLevel: "Eco Mode level", ecoPauseMedia: "Pause media", ecoLimitBackground: "Limit background", ecoDeepSleep: "Deep sleep", ecoDuration: "Duration", ecoUntilDisabled: "Until disabled", eco15Minutes: "15 minutes",
    ecoPreview_pause: "Pauses visible media and animations without blocking network requests.", ecoPreview_limit: "Blocks background media, XHR, WebSocket handshakes and pings; mutes the tab.", ecoPreview_deep: "Applies background limits and discards an inactive tab after warning.", ecoRecommended: "Recommended for this tab", ecoDeepConfirm: "Deep sleep will unload this inactive tab. Chrome will reload it when you return. Continue?", ecoDeepRiskConfirm: "This tab has an unsaved form or active media. Deep sleep can reload it and lose state. Continue?", ecoStatusActive: "Eco Mode active: {level}", ecoStatusRestoring: "Chrome is restoring the discarded tab…", ecoStatusRestored: "The tab was restored successfully.", ecoLevel_pause: "Pause media", ecoLevel_limit: "Limit background", ecoLevel_deep: "Deep sleep",
    staleUnsaved: "unsaved form", staleMedia: "active media", saveSelected: "Save selected", staleSaved: "Saved {count} tabs to a new bookmarks folder.", closeStaleRiskConfirm: "{risky} of {count} selected tabs may contain unsaved form data or active media. Close anyway?",
    bookmarkChecking: "Reviewing bookmarks…",
    watchHistoryRemove: "Remove saved position", watchHistoryCleaned: "removed: {parameters}",
    duplicateActive: "active copy", duplicateKeep: "keep this copy",
    siteResetResult_cookies: "Cookies", siteResetResult_storage: "Storage", siteResetResult_cache: "Cache", siteResetResult_serviceWorkers: "Service workers", siteResetResultDone: "removed", siteResetResultFailed: "failed",
    activityDataSettings: "Activity data", activityDataSettingsDescription: "Control local retention and sites excluded from analytics.", activityRetention: "Retention", activityReferenceHours: "Reference period, hours", activityExclusions: "Excluded sites",
    toolBehaviorSettings: "Tool behavior", toolBehaviorSettingsDescription: "Defaults for Eco Mode, video history and local request diagnostics.", ecoDefaultLevel: "Eco Mode default", continueRetention: "Continue Watching retention", blockingJournalEnabled: "Record a local blocking journal only while enabled", trackingCleanerEnabled: "Remove known tracking parameters from opened links", saveDataSettings: "Save data settings",
    diagnosticBundle: "Diagnostic bundle", diagnosticBundleDescription: "Exports the version, non-secret settings, active rule counts, permission state and recent local errors.", exportDiagnostics: "Export diagnostics", invalidCosmeticRules: "Invalid cosmetic selectors on lines: {lines}",
    blockedShare: "Blocked share", blockingSources: "Rule sources", blockingSourcesDescription: "Likely source associated with each blocked request.", blockingCategories: "Categories", blockingCategoriesDescription: "Ads, trackers, miners, telemetry and interruptions.", blockingJournal: "Local request journal", blockingJournalDescription: "Recorded only when explicitly enabled in Settings.", clearJournal: "Clear journal", journalTime: "Time", journalSite: "Site", journalResource: "Resource", journalSource: "Source", journalCategory: "Category", siteDiagnostics: "Current site diagnostics", siteDiagnosticsDescription: "Shows active protection that may affect the current page.", bypassOnce: "Bypass for one reload", bypassApplied: "Protection bypassed for this reload only.", siteExcluded: "The site was added to permanent exceptions.",
    indicatorProcessor: "Processor", indicatorNetwork: "Network", indicatorStability: "Stability", indicatorBackground: "Background", sponsorStatus: "SponsorBlock", sponsorStatus_available: "segments ready", sponsorStatus_none: "no segments", sponsorStatus_disabled: "disabled", sponsorStatus_unavailable: "unavailable",
    featureMapTitle: "Explore Browser Monitor",
    featureMapDescription: "Open a branch and choose a function to understand its role.",
    featureBranchProtection: "Protection", featureBranchPrivacy: "Privacy", featureBranchActivity: "Activity and tools", featureBranchControl: "Control and data",
    featureNetwork: "Network filters", featureCleanup: "Page cleanup", featureVideo: "Video protection", featureBrowserTools: "Browser tools",
    featureDetailProtectionLabel: "Protection", featureDetailPrivacyLabel: "Privacy", featureDetailActivityLabel: "Activity", featureDetailControlLabel: "Control",
    featureNetworkDetail: "Network filters stop advertising, tracking and mining requests before the page can load or run them. Separate lists let you choose the balance of coverage that suits your browsing.",
    featureNetworkFact: "Chrome applies declarative rules directly in its network layer.",
    featureCleanupDetail: "Page cleanup removes supported banners, subscription pop-ups, surveys, notification prompts and floating media so the page stays easier to read.",
    featureCleanupFact: "Targeted selectors and event rules match recognized page patterns as content appears.",
    featureVideoDetail: "Video protection blocks recognized player advertising, can pause unsolicited autoplay and skips community-marked sponsored segments when enabled.",
    featureVideoFact: "SponsorBlock identifies matching segments through a four-character SHA-256 prefix.",
    featureCryptoDetail: "Crypto Guard checks copied and pasted blockchain addresses for a sudden substitution that could redirect a payment. It works automatically during the brief moment when the address is used.",
    featureCryptoFact: "A five-minute SHA-256 fingerprint links the copy and paste checks across pages.",
    featureLinksDetail: "Link safety recognizes shortened, lookalike, punycode and nested-redirect destinations, then shows a clear warning before a risky transition.",
    featureLinksFact: "Allowed and blocked domain lists remain under your direct control.",
    featureHistoryDetail: "The history filter removes visits to selected domains and hides matching suggestions on supported search pages after you grant Chrome history access.",
    featureHistoryFact: "Matching is based on the registrable domain, so one rule covers its subdomains.",
    featureAnalysisDetail: "Tab analysis explains which open pages are heavy by combining processor work, layout changes, network volume, media and background behavior into a readable assessment.",
    featureAnalysisFact: "Measurements are aggregated into compact history inside the current browser profile.",
    featureEcoDetail: "Eco Mode reduces work in a chosen tab by pausing media, limiting background connections or putting an inactive tab into deep sleep.",
    featureEcoPauseDetail: "Pauses visible media and page animations while keeping the tab ready.",
    featureEcoLimitDetail: "Restricts background media, live connections, and ping activity and mutes the tab.",
    featureEcoDeepDetail: "Applies background limits and asks Chrome to unload an inactive tab after a warning.",
    featureEcoFact: "The selected mode can be reversed from the same tab control.",
    featureWatchingDetail: "Continue Watching remembers the position of recognized long-form videos and opens recent viewing directly at the saved moment.",
    featureWatchingFact: "Up to 100 recent positions are kept locally for the selected retention period.",
    featureToolsDetail: "Browser tools bring together site cleanup, cookie and storage inspection, tab review, bookmark health and site reset actions in the extension interface.",
    featureToolsFact: "Actions are started deliberately and report what changed before the tool closes.",
    featureAppearanceDetail: "Appearance controls the extension color scheme and can replace suitable blocked ad spaces with artwork you select.",
    featureAppearanceFact: "Image Swap reads the selected collection from browser-local storage.",
    featureRulesDetail: "Advanced rules let you define site exceptions, blocked destinations, hidden page elements and trusted filter-list subscriptions.",
    featureRulesFact: "Rules are validated before they are passed to Chrome's declarative filtering engine.",
    featureDataDetail: "Data and privacy controls retention, backups, tool defaults and diagnostic exports. Local-first storage keeps settings and compact summaries in the current browser profile.",
    featureDataFact: "Diagnostic export assembles the extension version, settings state, rule counts, permissions, and recent errors.",
    moreInformation: "More information", retention90Days: "90 days",
    backupTooltip: "Creates or restores a local JSON copy of extension settings and exceptions.",
    activityDataTooltip: "Sets how long compact activity summaries remain available and which sites are omitted from analysis.",
    toolBehaviorTooltip: "Sets default Eco Mode behavior, video-position retention, tracking-link cleanup and the optional blocking journal.",
    diagnosticTooltip: "Creates a troubleshooting file with version, settings state, rule counts, permissions and recent extension errors.",
    protectionModesTitle: "How protection modes work", protectionModesDescription: "Each control has a different scope.", modeGlobal: "Global protection", modeGlobalDescription: "Turns blocking on or off everywhere.", modePause: "Pause for this site", modePauseDescription: "Temporarily stops protection for the current site.", modeBypass: "One reload bypass", modeBypassDescription: "Skips protection only until the next completed reload.", modeExclude: "Permanent exception", modeExcludeDescription: "Keeps the site excluded until you remove it in Settings."
  },
  ru: {
    appName: "Browser Monitor",
    extensionEnabled: "Расширение включено",
    extensionPaused: "Browser Monitor приостановлен",
    settings: "Настройки",
    language: "Язык",
    english: "English",
    russian: "Русский",
    navAnalytics: "Аналитика",
    navGeneral: "Основные",
    navFilters: "Фильтры",
    navPageElements: "Элементы страниц",
    navLinkSafety: "Безопасность ссылок",
    navHistoryPrivacy: "Фильтр истории",
    navProtectionCenter: "Защита",
    navPrivacyTools: "Приватность",
    navProtection: "Защита",
    navComfort: "Комфорт",
    navAppearance: "Внешний вид",
    navRules: "Расширенные правила",
    navData: "Данные",
    navFeedback: "Обратная связь",
    heroEyebrow: "Защита браузера без лишнего шума",
    heroTitle: "Спокойнее страницы. Легче браузер.",
    heroDescription: "Блокируйте рекламу и слежение, убирайте помехи и находите причины нагрузки во вкладках. Все данные обрабатываются локально.",
    settingsTitle: "Настройки",
    settingsDescription: "Управляйте поведением расширения, инструментами страниц и локальными данными.",
    protectionOn: "Защита включена",
    protectionOff: "Защита выключена",
    activeRules: "активных сетевых правил",
    statusDescription: "Состояние основной защиты браузера",
    sectionGeneral: "Основные",
    sectionGeneralDescription: "Главные переключатели защиты и анализа вкладок.",
    sectionFilters: "Фильтры",
    sectionFiltersDescription: "Выберите сетевые и косметические списки, используемые расширением.",
    sectionProtectionCenter: "Защита",
    sectionProtectionCenterDescription: "Настройте, что Browser Monitor блокирует, скрывает или очищает при загрузке страниц.",
    filterListsGroup: "Сетевые фильтры и списки",
    filterListsGroupDescription: "Базовые правила блокировки рекламы, трекеров, майнеров и региональных рекламных ресурсов.",
    sectionPageElements: "Элементы страниц",
    sectionPageElementsDescription: "Настройте баннеры cookies, всплывающие окна, запросы, автовоспроизведение и плавающее видео.",
    pageCleanupGroup: "Очистка страниц",
    pageCleanupGroupDescription: "Дополнительные инструменты для оверлеев, запросов, видео-рекламы и рекламных интеграций.",
    sectionLinkSafety: "Безопасность ссылок",
    sectionLinkSafetyDescription: "Предупреждает перед переходом по ссылкам с фишинговыми или подозрительными признаками.",
    sectionHistoryPrivacy: "Фильтр истории",
    sectionHistoryPrivacyDescription: "Убирает выбранные домены из локальной истории Chrome и скрывает совпадающие поисковые подсказки на поддерживаемых поисковых страницах.",
    sectionPrivacyTools: "Приватность",
    sectionPrivacyToolsDescription: "Настройте предупреждения о ссылках, заблокированные переходы и локальную очистку истории в одном месте.",
    securityGroup: "Безопасность",
    securityGroupDescription: "Настройте защиту копирования, продолжение видео, отметки поиска и предупреждения о ссылках.",
    automaticProtectionGroup: "Автоматическая локальная защита",
    automaticProtectionGroupDescription: "Тихие функции без аккаунтов, облачных проверок и дополнительных переключателей.",
    alwaysOn: "Всегда включён",
    localOnlyBadge: "Локально",
    sectionAnalytics: "Аналитика вкладок",
    sectionAnalyticsDescription: "Посмотрите, какие открытые страницы создают нагрузку, почему это происходит и поможет ли пауза. Измерения остаются в этом профиле браузера.",
    refreshAnalytics: "Обновить анализ",
    analyticsUpdated: "Обновлено: {time}",
    openTabsStat: "Открытые вкладки",
    openTabsStatDescription: "Обычные веб-страницы, доступные для локального анализа.",
    attentionStat: "Требуют внимания",
    attentionStatDescription: "Тяжёлые и критические вкладки, которые стоит проверить.",
    activityHistory: "Недавняя активность",
    activityHistoryDescription: "Дневной пик нагрузки и число блокировок. В течение 90 дней хранятся только компактные итоги.",
    lastSevenDays: "7 дней",
    tabLoad: "Текущая нагрузка вкладок",
    tabLoadDescription: "Оценка учитывает блокировку основного потока, перерасчёт макета, сеть, медиа и фоновую активность.",
    noAnalyzedTabs: "Пока нет обычных веб-вкладок. Откройте сайт или включите анализ вкладок.",
    openTab: "Открыть вкладку",
    scoreLabel: "Оценка нагрузки",
    historyBlocked: "Заблокировано: {count}",
    historyScore: "пик {score}",
    sectionProtection: "Защита",
    sectionProtectionDescription: "Выберите, что Chrome будет блокировать до загрузки страницы. Декларативные правила работают внутри Chrome и не проверяют каждый запрос через JavaScript.",
    masterProtection: "Блокировать рекламу и трекеры",
    masterProtectionDescription: "Блокирует рекламу и трекеры и убирает поддерживаемые помехи на страницах.",
    tabAnalysis: "Анализировать активность вкладок",
    tabAnalysisDescription: "Находит вкладки с высокой нагрузкой на процессор, сеть, медиа или фон.",
    easyList: "Рекламные фильтры",
    easyListDescription: "Блокирует распространённые рекламные запросы и элементы страниц.",
    easyPrivacy: "Защита от слежения",
    easyPrivacyDescription: "Блокирует известные аналитические и рекламные трекеры.",
    crypto: "Защита от майнинга",
    cryptoDescription: "Останавливает известные скрипты браузерного майнинга.",
    cosmetic: "Убирать пустые места рекламы",
    cosmeticDescription: "Скрывает пустые контейнеры после блокировки рекламы.",
    russianFilters: "Фильтры русскоязычных страниц",
    russianFiltersDescription: "Добавляет правила RU AdList для русскоязычных сайтов.",
    socialFilters: "Отслеживающие социальные кнопки",
    socialFiltersDescription: "Скрывает социальные виджеты, отслеживающие посещения.",
    warningFilters: "Сообщения об отключении блокировщика",
    warningFiltersDescription: "Скрывает распространённые просьбы отключить блокировку рекламы.",
    sectionComfort: "Комфорт",
    sectionComfortDescription: "Дополнительные инструменты против элементов, мешающих чтению. Они не работают, пока вы сами их не включите.",
    cookieBanners: "Баннеры согласия на cookies",
    cookieBannersDescription: "Скрывает поддерживаемые окна согласия на cookies.",
    newsletters: "Окна подписки на рассылку",
    newslettersDescription: "Убирает распространённые формы подписки, закрывающие содержимое страницы.",
    surveys: "Предложения пройти опрос",
    surveysDescription: "Скрывает распространённые окна опросов и обратной связи.",
    notificationPrompts: "Предложения включить уведомления",
    notificationPromptsDescription: "Скрывает запросы сайтов на включение уведомлений.",
    autoplay: "Нежелательное автовоспроизведение",
    autoplayDescription: "Приостанавливает автоматически запущенные аудио и видео до взаимодействия со страницей.",
    floatingVideo: "Плавающее и закреплённое видео",
    floatingVideoDescription: "Скрывает видеоплееры, следующие за страницей при прокрутке.",
    videoAdProtection: "Реклама в видеоплеерах",
    videoAdProtectionDescription: "Блокирует распознанную рекламу в поддерживаемых видеоплеерах.",
    sponsorSkipping: "Рекламные интеграции",
    sponsorSkippingDescription: "Пропускает отмеченные сообществом SponsorBlock фрагменты на YouTube.",
    searchProtection: "Защита результатов поиска",
    searchProtectionDescription: "Показывает отметки доверия и предупреждения рядом с результатами поиска.",
    linkSafetyEnabled: "Предупреждения о подозрительных ссылках",
    linkSafetyEnabledDescription: "Открывает предупреждение Browser Monitor перед переходом на рискованные ссылки.",
    warnShorteners: "Сокращённые ссылки",
    warnShortenersDescription: "Предупреждает, когда назначение скрыто за популярным сервисом сокращения URL.",
    warnLookalikes: "Похожие домены",
    warnLookalikesDescription: "Предупреждает, когда адрес имитирует известный бренд, но настоящий домен другой.",
    warnPunycode: "Punycode и смешанные алфавиты",
    warnPunycodeDescription: "Предупреждает о доменах, которые могут скрывать похожие символы.",
    warnRedirects: "Вложенные редиректы",
    warnRedirectsDescription: "Предупреждает, когда параметры URL содержат другой адрес назначения.",
    warnUnknownFromSocial: "Ссылки из соцсетей",
    warnUnknownFromSocialDescription: "Усиливает предупреждения для рискованных ссылок из X, Reddit или Telegram Web.",
    linkSafetyAllowedDomains: "Разрешённые домены",
    linkSafetyAllowedDomainsDescription: "Не предупреждать для этих доменов или поддоменов. Один адрес на строку.",
    linkSafetyBlockedDomains: "Заблокированные домены",
    linkSafetyBlockedDomainsDescription: "Всегда показывать предупреждение для этих основных доменов.",
    domainListsTitle: "Списки доменов",
    domainListsDescription: "Управляйте адресами, которым всегда доверяете или которые всегда блокируются.",
    domainListsDialogDescription: "Добавляйте по одному домену или поддомену в строке.",
      builtInTrustedDomains: "Встроенный список официальных доменов сервисов: {count}. Здесь добавляются только личные исключения.",
    close: "Закрыть",
    cancel: "Отмена",
    saveLinkSafety: "Сохранить безопасность ссылок",
    historyPrivacyEnabled: "Скрывать выбранные домены из истории",
    historyPrivacyEnabledDescription: "После разрешения пользователя Browser Monitor удаляет совпадающие записи локальной истории Chrome.",
    historyPrivacyDomains: "Домены для скрытия",
    historyPrivacyDomainsDescription: "Один основной домен на строку, например youtube.com. Подсказки с этими названиями скрываются на страницах Google, Yandex и Bing.",
    saveHistoryPrivacy: "Сохранить фильтр истории",
    purgeHistoryPrivacy: "Очистить совпадения сейчас",
    cryptoGuardTitle: "Crypto Guard",
    cryptoGuardDescription: "Обнаруживает подмену блокчейн-адреса при копировании и вставке.",
    continueWatchingTitle: "Продолжить просмотр",
    continueWatchingDescription: "Восстанавливает сохранённую позицию в распознанных длинных видео.",
    sectionAppearance: "Внешний вид",
    sectionAppearanceDescription: "Настройте замену рекламы изображениями и тему интерфейса.",
    imageSwap: "Замена рекламы изображениями",
    imageSwapDescription: "Заменяет подходящие заблокированные рекламные места выбранными изображениями.",
    imageCollection: "Коллекция изображений",
    landscape: "Пейзаж",
    ocean: "Океан",
    minimal: "Минимализм",
    custom: "Мои изображения",
    customImages: "Ваши локальные изображения",
    customImagesDescription: "Добавьте до девяти JPG, PNG, WebP, GIF или BMP: до 1 МБ на файл и до 6 МБ суммарно. Изображения не покидают этот профиль браузера.",
    chooseImages: "Выбрать изображения",
    removeImages: "Удалить все",
    noCustomImages: "Изображения ещё не добавлены",
    imageCount: "Локальных изображений: {count}",
    interfaceTheme: "Тема расширения",
    interfaceThemeDescription: "Изменяет цветовую схему интерфейса расширения.",
    themeSystem: "Системная",
    themeLight: "Светлая",
    themeDark: "Тёмная",
    themeSolarized: "Solarized",
    themeForest: "Лесная",
    sectionRules: "Расширенные правила",
    sectionRulesDescription: "Управляйте исключениями сайтов, заблокированными доменами запросов, скрытыми элементами и HTTPS-подписками на списки фильтров.",
    siteExceptions: "Исключения для сайтов",
    siteExceptionsDescription: "На этих доменах защита выключена. Укажите по одному домену в строке, например example.com.",
    blockedDomains: "Блокируемые домены",
    blockedDomainsDescription: "Всегда блокировать запросы к этим доменам. До 1 000 записей.",
    cosmeticRules: "Скрытые элементы страниц",
    cosmeticRulesDescription: "CSS-селекторы, созданные инструментом выбора элемента или добавленные вручную. Ошибочные селекторы игнорируются.",
    filterSubscriptions: "Подписки на списки фильтров",
    filterSubscriptionsDescription: "Добавьте до двух прямых HTTPS-ссылок. Небезопасные разрешающие правила, redirect, scriptlet и неподдерживаемые конструкции отклоняются.",
    saveRules: "Сохранить правила",
    updateLists: "Обновить списки",
    updated: "Обновлено {time}",
    updateFailed: "Ошибка обновления: {error}",
    ruleSummary: "Сетевых: {network} · для страниц: {cosmetic}",
    sectionData: "Данные и приватность",
    sectionDataDescription: "Настройте хранение, поведение инструментов, резервные копии и диагностику.",
    localOnly: "Только локально",
    localOnlyDescription: "Настройки, аналитика вкладок и диагностика правил остаются на этом Mac. У Browser Monitor нет сервера аналитики или учётной записи.",
    backup: "Резервная копия и восстановление",
    backupDescription: "Экспортируйте настройки расширения или восстановите прежнюю копию.",
    exportSettings: "Экспортировать настройки",
    importSettings: "Импортировать настройки",
    resetSettings: "Вернуть значения по умолчанию",
    activityLauncherTitle: "Аналитика посещений · NEW",
    activityLauncherDescription: "Активное время, чтение и видео",
    activityHint: "Открыть аналитику посещений",
    feedbackButton: "Связь",
    feedbackHint: "Предложить инструмент или сообщить об ошибке",
    sectionFeedback: "Обратная связь",
    sectionFeedbackDescription: "Предложите новый инструмент или сообщите об ошибке. Перед отправкой запрос можно проверить.",
    feedbackCardTitle: "Помогите улучшить Browser Monitor",
    feedbackCardDescription: "Откройте короткую форму с почтой, описанием запроса и необязательным скриншотом.",
    contactIntro: "Также можно связаться с разработчиком напрямую.",
    openFeedback: "Открыть форму",
    backupReady: "Резервная копия настроек сохранена.",
    importReady: "Настройки восстановлены. Открытые страницы может потребоваться обновить.",
    invalidBackup: "Файл резервной копии повреждён или не поддерживается.",
    resetConfirm: "Вернуть все настройки защиты по умолчанию? Исключения и пользовательские правила будут удалены.",
    importConfirm: "Заменить текущие настройки защиты и исключения данными из этой копии?",
    saved: "Сохранено",
    saving: "Сохранение…",
    error: "Не удалось сохранить изменения.",
    openSettings: "Открыть настройки",
    collecting: "Сбор данных…",
    dataUnavailable: "Данные временно недоступны",
    dataTemporarilyUnavailable: "Показаны последние доступные данные",
    refreshToRetry: "Обновите, чтобы повторить",
    analysisPaused: "Анализ вкладок приостановлен",
    tabsSummary: "{tabs} · {attention}",
    tabsCountOne: "1 вкладка",
    tabsCountMany: "Вкладок: {count}",
    attentionOne: "1 требует внимания",
    attentionMany: "Требуют внимания: {count}",
    appConnected: "Приложение подключено",
    extensionOnly: "Только расширение",
    currentSite: "Текущий сайт",
    checkingAddress: "Проверка адреса…",
    excludeSite: "Исключить сайт",
    protectSite: "Защитить сайт",
    reportSite: "Сообщить о проблеме фильтров на этом сайте",
    allowedHere: "Реклама и трекеры разрешены",
    protectionActiveHere: "Реклама и трекеры блокируются на этом сайте",
    pausedUntil: "Пауза до {time}",
    pause10: "Пауза 10 мин",
    cleanupSiteDataHint: "Удалять данные входа после закрытия последней вкладки сайта",
    cleanupSiteDataEnabled: "Данные сайта будут удалены после закрытия его последней вкладки.",
    cleanupSiteDataDisabled: "Автоудаление данных для этого сайта выключено.",
    cleanupPermissionDenied: "Для удаления данных требуется разрешение Chrome.",
    resume: "Продолжить",
    resumeProtection: "Вернуть защиту",
    sitePausedNotice: "Защита этого сайта приостановлена на 10 минут. Нажмите иконку паузы ещё раз, чтобы вернуть её сразу.",
    siteProtectionResumed: "Защита этого сайта снова работает.",
    privacyReceipt: "Квитанция приватности сайта",
    privacyReceiptHint: "Показать локальную квитанцию приватности сайта",
    receiptBlocked: "DNR + защита",
    receiptThirdParty: "сетевые запросы",
    receiptCookies: "видимые странице cookies",
    receiptStorage: "ключи storage страницы",
    receiptLocalOnly: "Хранится локально только до конца этого визита.",
    receiptProtected: "Защищён",
    receiptPaused: "Пауза",
    receiptCollecting: "Сбор…",
    receiptObserved: "наблюдение {duration}",
    receiptDomains: "Доменов: {count} · запросов: {requests}: {domains}",
    receiptNoDomains: "Пока не замечено третьих лиц.",
    receiptDetailsButton: "Подробнее",
    receiptDetailsTitle: "Детали приватности сайта",
    receiptAllowedRequests: "Разрешено",
    receiptBlockedRequests: "Заблокировано",
    receiptUnknownRequests: "Другие ошибки",
    receiptNetworkSource: "Наблюдаемые сетевые запросы",
    receiptProtectionSource: "DNR и защита Browser Monitor",
    receiptUnknownSource: "Отменено, завершилось ошибкой или не классифицировано",
    receiptCategoryNote: "Назначение доменов определяется локальной эвристикой имени, а не подтверждённым владельцем.",
    receiptCategoryAds: "Реклама",
    receiptCategoryAnalytics: "Аналитика",
    receiptCategoryVideo: "Видео",
    receiptCategorySocial: "Соцсети",
    receiptCategoryCdn: "CDN",
    receiptCategoryOther: "Другое",
    blockedResources: "Заблокированные трекеры и ресурсы",
    thirdPartyConnections: "Сторонние подключения",
    noBlockedResources: "Нет заблокированных ресурсов.",
    noThirdPartyConnections: "Нет сторонних подключений.",
    exceptions: "Исключения",
    remove: "Удалить",
    tabActivity: "Активность вкладок",
    tools: "Инструменты",
    previousTools: "Предыдущие инструменты",
    nextTools: "Следующие инструменты",
    watchHistoryButton: "Видео",
    siteResetButton: "Сброс",
    siteResetHint: "Выбрать, что удалить сейчас или после закрытия текущей вкладки",
    siteResetTitle: "Сброс сайта",
    siteResetWarning: "Вы можете выйти из аккаунта, а несохранённые офлайн-данные могут быть потеряны.",
    siteResetCategories: "Что удалить",
    siteResetCookies: "Cookies",
    siteResetCookiesDetail: "Cookies входа и настроек",
    siteResetStorage: "Хранилища сайта",
    siteResetCache: "Кэш",
    siteResetWorkersDetail: "Фоновые обработчики сайта",
    siteResetWhen: "Когда удалить",
    siteResetNow: "Сейчас",
    siteResetOnClose: "После закрытия вкладки",
    siteResetAfter5: "Через 5 минут после закрытия",
    siteResetAfter30: "Через 30 минут после закрытия",
    siteResetAfter60: "Через час после закрытия",
    siteResetCloseNote: "Перезагрузка не запускает таймер. Отсчёт начнётся только после закрытия этой вкладки.",
    siteResetApply: "Запланировать сброс",
    siteResetChooseCategory: "Выберите хотя бы одну категорию данных.",
    siteResetConfirmNow: "Удалить выбранные данные сайта {site} сейчас? Действие необратимо.",
    siteResetConfirmSchedule: "Запланировать удаление выбранных данных сайта {site}?",
    siteResetDone: "Выбранные данные сайта удалены.",
    siteResetScheduled: "Сброс запланирован. Перезагрузка его не запустит.",
    siteResetFailed: "Не удалось выполнить сброс сайта.",
    reviewButton: "Разбор",
    reviewHint: "Проверить старые вкладки и структуру закладок в одном месте",
    reviewTitle: "Разбор браузера",
    reviewDescription: "Старые вкладки и структура закладок",
    reviewTabs: "Вкладки",
    reviewBookmarks: "Закладки",
    staleInactiveFor: "Неактивны",
    stale1Day: "1 день",
    stale7Days: "7 дней",
    stale30Days: "30 дней",
    staleNote: "Активные и закреплённые вкладки исключены.",
    staleEmpty: "За этот период старых вкладок нет.",
    staleDays: "{count} дн. без доступа",
    selectAll: "Выбрать все",
    closeSelected: "Закрыть выбранные",
    closeStaleConfirm: "Закрыть выбранные вкладки: {count}?",
    staleClosed: "Закрыто вкладок: {count}.",
    bookmarkReviewNote: "Локально находит некорректные и повторяющиеся адреса. Сайты из закладок не запрашиваются.",
    scanBookmarks: "Разрешить и проверить",
    scanBookmarksAgain: "Проверить закладки",
    bookmarksPermissionPrompt: "Доступ к закладкам нужен Browser Monitor только для локальной проверки названий и адресов.",
    bookmarkStartScan: "Запустите проверку структуры закладок.",
    bookmarkNoIssues: "Структурных проблем не найдено.",
    bookmarkHealthy: "Проверено закладок: {count}. Структурных проблем нет.",
    bookmarkIssuesFound: "Найдено для проверки: {count}.",
    bookmarkDuplicate: "Повторяющийся адрес",
    bookmarkInvalid: "Некорректный адрес",
    bookmarkScanFailed: "Не удалось прочитать закладки. Попробуйте ещё раз.",
    back: "Назад",
    duplicateTabsButton: "Дубликаты",
    duplicateTabsHint: "Найти вкладки-дубликаты",
    duplicateTabsTitle: "Вкладки-дубликаты",
    duplicateTabsDescription: "Совпадающие страницы без учёта tracking-параметров",
    closeDuplicateTabs: "Закрыть дубликаты",
    noDuplicateTabs: "Вкладок-дубликатов нет.",
    duplicateCopies: "Совпадающих вкладок: {count}",
    watchHistoryHint: "Показать недавно просмотренные видео",
    watchHistoryTitle: "Недавно смотрели",
    closeWatchHistory: "Закрыть список просмотренного",
    watchHistoryLoading: "Загружаем последние видео…",
    watchHistoryEmpty: "Здесь появятся фильмы, серии и длинные ролики, просмотр которых вы остановили.",
    watchHistoryUntitled: "Видео без названия",
    watchHistoryEpisode: "Серия",
    watchHistoryMovie: "Фильм",
    watchHistoryVideo: "Ролик",
    watchHistoryOpen: "Открыть на сайте {site}",
    statisticsButton: "Статистика",
    statisticsHint: "Открыть статистику блокировок",
    statisticsTitle: "Активность защиты",
    statisticsDescription: "Приватная локальная статистика Browser Monitor.",
    liveUpdates: "Обновляется в реальном времени",
    blockedToday: "Заблокировано сегодня",
    blockedSevenDays: "За последние 7 дней",
    rollingWindow: "Скользящий локальный период",
    networkRequests: "Сеть",
    videoAndSponsors: "Видео и интеграции",
    sevenDayActivity: "Активность за семь дней",
    sevenDayActivityDescription: "Заблокированные запросы и распознанные рекламные фрагменты.",
    topBlockedSites: "Топ сайтов",
    topBlockedSitesDescription: "Страницы, где защита срабатывала чаще всего.",
    blockedResources: "Заблокированные ресурсы",
    blockedResourcesDescription: "Домены и категории видеорекламы, остановленные защитой.",
    noBlockingActivity: "Блокировок пока не было.",
    noBlockedResources: "Заблокированные ресурсы появятся здесь.",
    statisticsPrivacy: "Локально хранятся только компактные счётчики за семь дней. Полные адреса страниц не сохраняются; результат SponsorBlock может хранить ID видео YouTube до 12 часов.",
    clearStatistics: "Очистить статистику",
    clearStatisticsConfirm: "Удалить всю локальную статистику блокировок?",
    statisticsBreakdown: "Сеть: {network} · видео: {video} · интеграции: {sponsor}",
    waitingForBlocks: "Ожидание активности",
    cookies: "Cookies",
    cookieToolHint: "Просмотреть и экспортировать cookies текущего сайта после предоставления доступа Chrome",
    blockElement: "Скрыть",
    refresh: "Обновить",
    tabDetails: "Сведения о вкладке",
    whyItMatters: "Почему это важно",
    recommendation: "Рекомендация",
    export: "Экспорт",
    saveAs: "Сохранить как",
    copy: "Копировать",
    exportAllCookies: "Экспортировать все cookies браузера",
    exportFormat: "Формат экспорта",
    cookieDomain: "Домен",
    cookieIdentity: "Cookie",
    cookieProtection: "Защита",
    cookieUnnamed: "Без имени",
    cookieValueHidden: "Значение скрыто в Browser Monitor",
    cookieRevealValue: "Показать значение этой cookie",
    cookieHideValue: "Скрыть значение этой cookie",
    cookieEmptyValue: "У этой cookie пустое значение",
    cookieSecure: "Передаётся по защищённому соединению",
    cookieHttpOnly: "Скрыто от скриптов страницы",
    cookieNoProtectionFlags: "Нет флагов Secure или HttpOnly",
    cookieSession: "Сессия",
    cookiePersistent: "Постоянная",
    cookieSessionHint: "Удаляется после завершения сессии браузера",
    cookieExpires: "Истекает {date}",
    cookieSameSiteMissing: "Нет SameSite",
    cookieSameSiteHint: "Политика межсайтовой передачи cookie по данным Chrome",
    cookiePartitioned: "Разделена",
    cookiePartitionedHint: "Хранится в разделённом cookie-хранилище",
    cookieScriptAccessible: "Доступна JavaScript страницы, потому что отсутствует HttpOnly",
    cookieScriptAccessibleShort: "Доступ скриптов",
    cookieLongLived: "400д+",
    cookieLongLivedHint: "Срок действия превышает 400 дней",
    cookieAdvanced: "Расширенный экспорт всех сайтов",
    cookieAdvancedWarning: "Включает cookies входа со всех сайтов. Используйте только для осознанной резервной копии.",
    storageMapTitle: "Карта хранилищ сайта",
    storageMapSource: "Проверка страницы · приблизительный объём origin",
    storageQuota: "Квота",
    cookieChangesTitle: "Изменения в этой сессии браузера",
    cookieChangesEmpty: "Изменений cookies этого сайта пока не замечено.",
    cookieChangeCreated: "Создана",
    cookieChangeUpdated: "Обновлена",
    cookieChangeRemoved: "Удалена",
    cookieHistoryOpen: "Открыть историю cookies и экспорт всего браузера",
    cookieHistoryTitle: "История cookies",
    cookieHistoryDescription: "Изменения без значений, замеченные в течение этой сессии браузера.",
    cookieHistoryPrivacy: "Значения cookies никогда не сохраняются в этой истории.",
    cookieHistoryTime: "Время",
    cookieHistoryEvent: "Событие",
    cookieHistoryEmpty: "В этой сессии браузера изменений cookies пока не замечено.",
    cookieHistorySessionNote: "История хранится локально до 12 часов и очищается вместе с сессией браузера.",
    cookieBrowserScope: "Весь браузер",
    cookieBrowserExportTitle: "Экспорт всех cookies",
    cookieBrowserExportDescription: "Создаёт одну локальную резервную копию cookies со всех сайтов браузера.",
    cookieAccessTitle: "Нужен доступ к cookies",
    cookieAccessDescription: "Предоставьте доступ для записи изменений без значений и экспорта cookies всего браузера.",
    cookieGrantAccess: "Предоставить доступ",
    noCookies: "Cookies для этого сайта не найдены.",
    cookieWarning: "Файл cookies может дать доступ к аккаунтам. Храните его в безопасном месте.",
    settingsHint: "Все функции защиты и понятные объяснения",
    openRegularPage: "Откройте обычную веб-страницу, чтобы увидеть её активность.",
    turnAnalysisOn: "Включите анализ, чтобы отслеживать нагрузку вкладок.",
    untitled: "Без названия",
    noSignificantLoad: "Заметных источников нагрузки не обнаружено",
    pauseTab: "Пауза",
    resumeTab: "Вернуть",
    restoreTabActivity: "Вернуть обычную активность вкладки",
    pauseTabActivity: "Приостановить медиа, анимации и фоновую сеть",
    activeTab: "Активная вкладка",
    backgroundTab: "Фоновая вкладка",
    recentlyBackground: "Недавно перешла в фон",
    backgroundFor: "В фоне {duration}",
    visibleTab: "Видимая вкладка",
    noActionNeeded: "Сейчас никаких действий не требуется.",
    metricLongFrames: "Долгие кадры",
    metricBlocking: "Блокировка",
    metricLayout: "Макет",
    metricResources: "Ресурсы",
    metricTransferred: "Загружено",
    metricBackground: "Фон",
    metricMedia: "Медиа",
    metricSample: "Период",
    measurementFull: "полное измерение",
    measurementPartial: "частичное измерение",
    measurementUnavailable: "измерение недоступно",
    durationSeconds: "{count} с",
    durationMinutes: "{count} мин",
    pauseThisTab: "Приостановить эту вкладку",
    resumeNormalTab: "Вернуть обычную работу вкладки",
    internalUnavailable: "Недоступно на служебных страницах Chrome",
    pictureInPictureActive: "Режим «картинка в картинке» активен",
    noVideoFound: "В текущей вкладке видео не найдено",
    videoFoundOne: "Найден 1 видеоэлемент",
    videoFoundMany: "Найдено видеоэлементов: {count}",
    reloadAfterInstall: "Обновите страницу после установки расширения",
    openingPiP: "Открытие режима «картинка в картинке»…",
    readingCookies: "Локальное чтение cookies…",
    preparingExport: "Подготовка экспорта…",
    preparingCopy: "Подготовка приватной копии…",
    cookiesCopied: "Скопировано cookies: {count}. Вставляйте только в надёжное место.",
    cookiesExported: "Экспортировано cookies: {count}. Файл: {filename}",
    cookieExportFailed: "Не удалось экспортировать cookies",
    permissionRequired: "Доступ не предоставлен. При необходимости можно повторить попытку.",
    permissionCancelled: "Запрос разрешения отменён.",
    cookiesPermissionPrompt: "Browser Monitor требуется доступ Chrome к cookies для проверки текущего сайта. Значения остаются на этом устройстве. Продолжить?",
    downloadsPermissionPrompt: "Browser Monitor требуется доступ к загрузкам только для сохранения запрошенного файла экспорта. Продолжить?",
    clipboardWritePermissionPrompt: "Browser Monitor требуется доступ к буферу обмена только для копирования этого экспорта после вашего действия. Продолжить?",
    browsingDataPermissionPrompt: "Browser Monitor требуется доступ к данным сайтов, чтобы удалить cookies и хранилища этого сайта после закрытия его последней вкладки. Продолжить?",
    historyPermissionPrompt: "Browser Monitor требуется доступ к истории для удаления посещений только добавленных вами доменов. Содержимое истории никуда не отправляется. Продолжить?",
    settingsDownloadPermissionPrompt: "Browser Monitor требуется доступ к загрузкам только для сохранения локальной резервной копии настроек. Продолжить?",
    exportAllConfirm: "Экспортировать все cookies браузера? Этот файл может дать доступ к авторизованным аккаунтам. Храните его безопасно и никому не передавайте.",
    filtersCount: "{network} + {cosmetic} фильтров",
    reasonLongBlocks: "Долгие блокировки основного потока",
    reasonLayout: "Частый перерасчёт стилей и макета",
    reasonLayoutShift: "Заметная нестабильность макета",
    reasonNetwork: "Большой объём сетевых ресурсов",
    reasonResourceCount: "Большое количество ресурсов страницы",
    reasonBackground: "Активность продолжается в фоне",
    reasonMedia: "На странице работают медиаэлементы",
    recommendationNormal: "Эту вкладку можно оставить открытой.",
    recommendationNoticeable: "Следите за этой вкладкой, особенно в фоновом режиме.",
    recommendationHeavy: "Приостановите медиа или обновите вкладку.",
    recommendationCritical: "Закройте вкладку, если она сейчас не нужна.",
    severityNormal: "норма",
    severityNoticeable: "заметная",
    severityHeavy: "высокая",
    severityCritical: "критическая",
    metricRecent: "Последние 60 секунд", metricTotal: "С момента открытия", backgroundTimeline: "Хронология фоновой активности", backgroundTimelineEmpty: "За последние 60 секунд фоновых событий нет.",
    "timeline_request": "запрос", "timeline_long-frame": "долгий кадр", "timeline_layout-shift": "сдвиг макета",
    ecoLevel: "Уровень Eco Mode", ecoPauseMedia: "Остановить медиа", ecoLimitBackground: "Ограничить фон", ecoDeepSleep: "Глубокий сон", ecoDuration: "Продолжительность", ecoUntilDisabled: "До отключения", eco15Minutes: "15 минут",
    ecoPreview_pause: "Останавливает видимые медиа и анимации без блокировки сетевых запросов.", ecoPreview_limit: "Блокирует фоновые media, XHR, WebSocket-соединения и ping; выключает звук вкладки.", ecoPreview_deep: "Применяет фоновые ограничения и выгружает неактивную вкладку после предупреждения.", ecoRecommended: "Рекомендуется для этой вкладки", ecoDeepConfirm: "Глубокий сон выгрузит неактивную вкладку. Chrome перезагрузит её, когда вы вернётесь. Продолжить?", ecoDeepRiskConfirm: "Во вкладке есть несохранённая форма или активное медиа. Глубокий сон может перезагрузить её и потерять состояние. Продолжить?", ecoStatusActive: "Eco Mode активен: {level}", ecoStatusRestoring: "Chrome восстанавливает выгруженную вкладку…", ecoStatusRestored: "Вкладка успешно восстановлена.", ecoLevel_pause: "Остановка медиа", ecoLevel_limit: "Ограничение фона", ecoLevel_deep: "Глубокий сон",
    staleUnsaved: "несохранённая форма", staleMedia: "активное медиа", saveSelected: "Сохранить выбранные", staleSaved: "В новую папку закладок сохранено вкладок: {count}.", closeStaleRiskConfirm: "В {risky} из {count} вкладок могут быть несохранённые формы или активное медиа. Всё равно закрыть?",
    bookmarkChecking: "Проверка закладок…",
    watchHistoryRemove: "Удалить сохранённую позицию", watchHistoryCleaned: "удалено: {parameters}",
    duplicateActive: "активная копия", duplicateKeep: "оставить эту копию",
    siteResetResult_cookies: "Cookies", siteResetResult_storage: "Хранилища", siteResetResult_cache: "Кеш", siteResetResult_serviceWorkers: "Service workers", siteResetResultDone: "удалено", siteResetResultFailed: "ошибка",
    activityDataSettings: "Данные активности", activityDataSettingsDescription: "Настройте локальный срок хранения и сайты, исключённые из аналитики.", activityRetention: "Срок хранения", activityReferenceHours: "Контрольный период, часы", activityExclusions: "Исключённые сайты",
    toolBehaviorSettings: "Поведение инструментов", toolBehaviorSettingsDescription: "Настройки Eco Mode, истории видео и локальной диагностики запросов.", ecoDefaultLevel: "Eco Mode по умолчанию", continueRetention: "Хранение Continue Watching", blockingJournalEnabled: "Вести локальный журнал блокировок только при включении", trackingCleanerEnabled: "Удалять известные параметры отслеживания из открываемых ссылок", saveDataSettings: "Сохранить настройки данных",
    diagnosticBundle: "Диагностический пакет", diagnosticBundleDescription: "Экспортирует версию, настройки без секретов, количество правил, разрешения и недавние локальные ошибки.", exportDiagnostics: "Экспортировать диагностику", invalidCosmeticRules: "Некорректные CSS-селекторы в строках: {lines}",
    blockedShare: "Доля блокировок", blockingSources: "Источники правил", blockingSourcesDescription: "Вероятный источник правила для каждого заблокированного запроса.", blockingCategories: "Категории", blockingCategoriesDescription: "Реклама, трекеры, майнеры, телеметрия и помехи.", blockingJournal: "Локальный журнал запросов", blockingJournalDescription: "Записывается только после явного включения в настройках.", clearJournal: "Очистить журнал", journalTime: "Время", journalSite: "Сайт", journalResource: "Ресурс", journalSource: "Источник", journalCategory: "Категория", siteDiagnostics: "Диагностика текущего сайта", siteDiagnosticsDescription: "Показывает активные функции защиты, которые могут влиять на страницу.", bypassOnce: "Пропустить на одно обновление", bypassApplied: "Защита отключена только для этого обновления.", siteExcluded: "Сайт добавлен в постоянные исключения.",
    indicatorProcessor: "Процессор", indicatorNetwork: "Сеть", indicatorStability: "Стабильность", indicatorBackground: "Фон", sponsorStatus: "SponsorBlock", sponsorStatus_available: "сегменты готовы", sponsorStatus_none: "сегментов нет", sponsorStatus_disabled: "отключён", sponsorStatus_unavailable: "недоступен",
    featureMapTitle: "Возможности Browser Monitor",
    featureMapDescription: "Откройте ветвь и выберите функцию, чтобы узнать о её роли.",
    featureBranchProtection: "Защита", featureBranchPrivacy: "Приватность", featureBranchActivity: "Активность и инструменты", featureBranchControl: "Управление и данные",
    featureNetwork: "Сетевые фильтры", featureCleanup: "Очистка страниц", featureVideo: "Защита видео", featureBrowserTools: "Инструменты браузера",
    featureDetailProtectionLabel: "Защита", featureDetailPrivacyLabel: "Приватность", featureDetailActivityLabel: "Активность", featureDetailControlLabel: "Управление",
    featureNetworkDetail: "Сетевые фильтры останавливают рекламные, отслеживающие и майнинговые запросы до их загрузки или запуска на странице. Отдельные списки позволяют выбрать подходящий уровень охвата.",
    featureNetworkFact: "Chrome применяет декларативные правила непосредственно на сетевом уровне.",
    featureCleanupDetail: "Очистка страниц убирает поддерживаемые баннеры, окна подписки, опросы, запросы уведомлений и плавающие медиа, чтобы содержимое было легче читать.",
    featureCleanupFact: "Точечные селекторы и событийные правила распознают нужные элементы по мере их появления.",
    featureVideoDetail: "Защита видео блокирует распознанную рекламу в плеерах, может останавливать нежелательное автовоспроизведение и пропускать отмеченные сообществом рекламные интеграции.",
    featureVideoFact: "SponsorBlock определяет подходящие сегменты через четырёхсимвольный SHA-256-префикс.",
    featureCryptoDetail: "Crypto Guard проверяет скопированные и вставленные блокчейн-адреса на внезапную подмену, способную перенаправить перевод. Проверка работает автоматически в момент использования адреса.",
    featureCryptoFact: "Пятиминутный SHA-256-отпечаток связывает проверку копирования с последующей вставкой между страницами.",
    featureLinksDetail: "Безопасность ссылок распознаёт сокращённые и похожие домены, punycode и вложенные редиректы, а затем показывает понятное предупреждение до рискованного перехода.",
    featureLinksFact: "Списки разрешённых и заблокированных доменов полностью управляются вами.",
    featureHistoryDetail: "Фильтр истории удаляет посещения выбранных доменов и скрывает совпадающие подсказки на поддерживаемых страницах поиска после выдачи разрешения Chrome.",
    featureHistoryFact: "Сопоставление идёт по основному домену, поэтому одно правило охватывает его поддомены.",
    featureAnalysisDetail: "Анализ вкладок объясняет нагрузку открытых страниц, объединяя работу процессора, изменения макета, объём сети, медиа и фоновое поведение в понятную оценку.",
    featureAnalysisFact: "Измерения объединяются в компактную историю внутри текущего профиля браузера.",
    featureEcoDetail: "Eco Mode снижает работу выбранной вкладки: останавливает медиа, ограничивает фоновые соединения или переводит неактивную вкладку в глубокий сон.",
    featureEcoPauseDetail: "Останавливает видимые медиа и анимации, сохраняя вкладку готовой к работе.",
    featureEcoLimitDetail: "Ограничивает фоновые медиа, постоянные соединения и ping-запросы и выключает звук вкладки.",
    featureEcoDeepDetail: "Применяет фоновые ограничения и после предупреждения просит Chrome выгрузить неактивную вкладку.",
    featureEcoFact: "Выбранный режим можно отменить тем же элементом управления вкладкой.",
    featureWatchingDetail: "«Продолжить просмотр» запоминает позицию в распознанных длинных видео и открывает недавний просмотр сразу на сохранённом моменте.",
    featureWatchingFact: "До 100 последних позиций хранятся локально в течение выбранного срока.",
    featureToolsDetail: "Инструменты браузера объединяют очистку сайта, проверку cookies и хранилищ, обзор вкладок, здоровье закладок и сброс сайта внутри интерфейса расширения.",
    featureToolsFact: "Действия запускаются явно и показывают результат выполненной операции.",
    featureAppearanceDetail: "Внешний вид управляет цветовой схемой расширения и может заменять подходящие заблокированные рекламные места выбранными изображениями.",
    featureAppearanceFact: "Image Swap читает выбранную коллекцию из локального хранилища браузера.",
    featureRulesDetail: "Расширенные правила позволяют задавать исключения сайтов, блокируемые адреса, скрытые элементы страниц и доверенные подписки на списки фильтров.",
    featureRulesFact: "Правила проверяются до передачи в декларативный механизм фильтрации Chrome.",
    featureDataDetail: "«Данные и приватность» управляет сроками хранения, резервными копиями, поведением инструментов и экспортом диагностики. Локальное хранение сохраняет настройки и компактные итоги в текущем профиле браузера.",
    featureDataFact: "Диагностический экспорт собирает версию расширения, состояние настроек, число правил, разрешения и недавние ошибки.",
    moreInformation: "Подробнее", retention90Days: "90 дней",
    backupTooltip: "Создаёт или восстанавливает локальную JSON-копию настроек и исключений расширения.",
    activityDataTooltip: "Задаёт срок хранения компактных итогов активности и сайты, исключённые из анализа.",
    toolBehaviorTooltip: "Задаёт Eco Mode по умолчанию, хранение позиций видео, очистку ссылок и необязательный журнал блокировок.",
    diagnosticTooltip: "Создаёт файл для диагностики с версией, состоянием настроек, числом правил, разрешениями и недавними ошибками расширения.",
    protectionModesTitle: "Как работают режимы защиты", protectionModesDescription: "У каждого элемента управления своя область действия.", modeGlobal: "Глобальная защита", modeGlobalDescription: "Включает или выключает блокировку на всех сайтах.", modePause: "Пауза для сайта", modePauseDescription: "Временно останавливает защиту на текущем сайте.", modeBypass: "Пропуск одного обновления", modeBypassDescription: "Отключает защиту только до завершения следующего обновления.", modeExclude: "Постоянное исключение", modeExcludeDescription: "Сайт остаётся исключённым, пока вы не удалите его в настройках."
  }
};

export function normalizeLanguage(value) {
  return SUPPORTED_LANGUAGES.includes(value) ? value : "en";
}

export function browserLanguage() {
  return normalizeLanguage((navigator.language || "en").toLowerCase().startsWith("ru") ? "ru" : "en");
}

export function translate(language, key, values = {}) {
  const template = messages[normalizeLanguage(language)][key] ?? messages.en[key] ?? key;
  return Object.entries(values).reduce(
    (result, [name, value]) => result.replaceAll(`{${name}}`, String(value)),
    template
  );
}

export function localizeDocument(language, root = document) {
  const normalized = normalizeLanguage(language);
  document.documentElement.lang = normalized;
  for (const element of root.querySelectorAll("[data-i18n]")) {
    element.textContent = translate(normalized, element.dataset.i18n);
  }
  for (const element of root.querySelectorAll("[data-i18n-title]")) {
    element.title = translate(normalized, element.dataset.i18nTitle);
  }
  for (const element of root.querySelectorAll("[data-i18n-aria]")) {
    element.setAttribute("aria-label", translate(normalized, element.dataset.i18nAria));
  }
  return normalized;
}
