export const SUPPORTED_LANGUAGES = ["en", "ru"];

const messages = {
  en: {
    appName: "Browser Monitor",
    extensionEnabled: "Extension enabled",
    extensionPaused: "Browser Monitor is paused",
    settings: "Settings",
    language: "Language",
    english: "English",
    russian: "Русский",
    navAnalytics: "Analytics",
    navGeneral: "General",
    navFilters: "Filters",
    navPageElements: "Page elements",
    navLinkSafety: "Link safety",
    navHistoryPrivacy: "History filter",
    navProtectionCenter: "Protection",
    navPrivacyTools: "Privacy",
    navProtection: "Protection",
    navComfort: "Comfort",
    navAppearance: "Appearance",
    navRules: "Advanced rules",
    navData: "Data",
    navFeedback: "Feedback",
    heroEyebrow: "Browser protection, without the noise",
    heroTitle: "Your browser, calmer and lighter.",
    heroDescription: "Block ads and trackers, remove interruptions, and understand what slows down every tab. Everything is processed locally.",
    settingsTitle: "Settings",
    settingsDescription: "Manage extension behavior, page tools, and local data.",
    protectionOn: "Protection is on",
    protectionOff: "Protection is off",
    activeRules: "active network rules",
    statusDescription: "Main browser protection status",
    sectionGeneral: "General",
    sectionGeneralDescription: "Main protection and tab-analysis switches.",
    sectionFilters: "Filters",
    sectionFiltersDescription: "Choose the network and page filter lists used by the extension.",
    sectionProtectionCenter: "Protection",
    sectionProtectionCenterDescription: "Choose what Browser Monitor blocks, hides, or cleans up while pages load.",
    filterListsGroup: "Network and list filters",
    filterListsGroupDescription: "Core blocking rules that stop ads, trackers, cryptominers, and regional advertising resources.",
    sectionPageElements: "Page elements",
    sectionPageElementsDescription: "Control cookie banners, pop-ups, prompts, autoplay, and floating video.",
    pageCleanupGroup: "Page cleanup",
    pageCleanupGroupDescription: "Optional controls for overlays, prompts, video interruptions, and sponsored segments.",
    sectionLinkSafety: "Link safety",
    sectionLinkSafetyDescription: "Warn before opening links with phishing-style or suspicious destination signals.",
    sectionHistoryPrivacy: "History filter",
    sectionHistoryPrivacyDescription: "Keep selected domains out of local Chrome history and hide matching search suggestions on supported search pages.",
    sectionPrivacyTools: "Privacy",
    sectionPrivacyToolsDescription: "Manage suspicious-link warnings, blocked destinations, and local history cleanup in one place.",
    sectionAnalytics: "Tab analytics",
    sectionAnalyticsDescription: "See which open pages are working hardest, why they are heavy, and whether pausing them will help. Measurements stay inside this browser profile.",
    refreshAnalytics: "Refresh analysis",
    analyticsUpdated: "Updated {time}",
    openTabsStat: "Open tabs",
    openTabsStatDescription: "Regular web pages available for local analysis.",
    attentionStat: "Need attention",
    attentionStatDescription: "Heavy or critical tabs worth reviewing.",
    activityHistory: "Recent activity",
    activityHistoryDescription: "Daily peak tab load and blocked requests. Only compact totals are kept for 90 days.",
    lastSevenDays: "7 days",
    tabLoad: "Current tab load",
    tabLoadDescription: "Scores combine main-thread blocking, layout work, network volume, media, and background activity.",
    noAnalyzedTabs: "No regular web tabs are available yet. Open a website or enable tab analysis.",
    openTab: "Open tab",
    scoreLabel: "Load score",
    historyBlocked: "{count} blocked",
    historyScore: "peak {score}",
    sectionProtection: "Protection",
    sectionProtectionDescription: "Choose what Chrome blocks before a page loads. Declarative rules run inside Chrome and do not inspect every request in JavaScript.",
    masterProtection: "Block ads and trackers",
    masterProtectionDescription: "The main switch for network and page-level protection. Site exceptions still apply.",
    tabAnalysis: "Analyze tab activity",
    tabAnalysisDescription: "Measures long tasks, layout work, downloads, media, and background activity to explain heavy tabs.",
    easyList: "Advertising filters",
    easyListDescription: "EasyList blocks common banners, video ads, ad servers, and intrusive promotional resources.",
    easyPrivacy: "Tracking protection",
    easyPrivacyDescription: "EasyPrivacy blocks analytics and advertising trackers that follow activity between sites.",
    crypto: "Cryptomining protection",
    cryptoDescription: "Stops known browser-mining scripts from using your processor without permission.",
    cosmetic: "Clean empty ad spaces",
    cosmeticDescription: "Hides leftover ad containers after their network requests have been blocked.",
    russianFilters: "Russian-language page filters",
    russianFiltersDescription: "Adds RU AdList network and page rules for advertising on Russian-language websites.",
    socialFilters: "Tracking social widgets",
    socialFiltersDescription: "Hides social buttons that can track visits. Some social sign-in buttons may also disappear.",
    warningFilters: "Ad-block warning messages",
    warningFiltersDescription: "Hides common requests to disable protection. It does not bypass paywalls or access restrictions.",
    sectionComfort: "Comfort",
    sectionComfortDescription: "Optional controls for the things that interrupt reading. These are off until you choose to enable them.",
    cookieBanners: "Cookie consent banners",
    cookieBannersDescription: "Hides supported consent overlays without accepting optional tracking cookies on your behalf.",
    newsletters: "Newsletter pop-ups",
    newslettersDescription: "Removes common e-mail subscription dialogs that cover page content.",
    surveys: "Survey requests",
    surveysDescription: "Hides common survey dialogs and feedback overlays.",
    notificationPrompts: "Notification prompts",
    notificationPromptsDescription: "Hides custom website prompts asking you to enable push notifications. Browser permission dialogs are not bypassed.",
    autoplay: "Unsolicited autoplay",
    autoplayDescription: "Pauses autoplaying audio and video until you interact with the page.",
    floatingVideo: "Floating and sticky video",
    floatingVideoDescription: "Hides videos that follow the page while you scroll. Regular inline players remain available.",
    videoAdProtection: "Video-player ads",
    videoAdProtectionDescription: "Blocks known VAST, VPAID, and IMA ad resources and removes recognized YouTube and Rutube ad controls. Normal video is changed only when an explicit ad marker is present.",
    sponsorSkipping: "Sponsored integrations",
    sponsorSkippingDescription: "Skips SponsorBlock community segments on YouTube. The lookup sends only a four-character SHA-256 prefix, never your full video address.",
    linkSafetyEnabled: "Suspicious link warnings",
    linkSafetyEnabledDescription: "Open a Browser Monitor warning page before visiting links that look risky.",
    warnShorteners: "Shortened links",
    warnShortenersDescription: "Warn when the destination is hidden behind common URL shorteners.",
    warnLookalikes: "Lookalike domains",
    warnLookalikesDescription: "Warn when a hostname imitates a known brand but the real domain is different.",
    warnPunycode: "Punycode and mixed alphabets",
    warnPunycodeDescription: "Warn about domains that may hide confusing characters.",
    warnRedirects: "Nested redirects",
    warnRedirectsDescription: "Warn when URL parameters contain another destination URL.",
    warnUnknownFromSocial: "Social-feed links",
    warnUnknownFromSocialDescription: "Raise warnings for risky links leaving social sites such as X, Reddit, or Telegram Web.",
    linkSafetyAllowedDomains: "Allowed domains",
    linkSafetyAllowedDomainsDescription: "Never warn for these registrable domains. Enter one domain per line.",
    linkSafetyBlockedDomains: "Blocked domains",
    linkSafetyBlockedDomainsDescription: "Always show the warning page for these registrable domains.",
    saveLinkSafety: "Save link safety",
    historyPrivacyEnabled: "Hide selected domains from history",
    historyPrivacyEnabledDescription: "When enabled, Browser Monitor removes matching local Chrome history entries after direct user permission.",
    historyPrivacyDomains: "Domains to hide",
    historyPrivacyDomainsDescription: "One registrable domain per line, for example youtube.com. Search suggestions containing these names are hidden on Google, Yandex, and Bing pages.",
    saveHistoryPrivacy: "Save history filter",
    purgeHistoryPrivacy: "Clean matching history now",
    sectionAppearance: "Appearance",
    sectionAppearanceDescription: "Configure Image Swap and the interface theme.",
    imageSwap: "Image Swap",
    imageSwapDescription: "Replaces up to two suitable blocked ad spaces with local artwork. Scanning stops after both replacements are made.",
    imageCollection: "Artwork collection",
    landscape: "Landscape",
    ocean: "Ocean",
    minimal: "Minimal",
    custom: "My images",
    customImages: "Your local images",
    customImagesDescription: "Add up to nine JPG, PNG, WebP, GIF, or BMP images. Each file must be under 1 MB, with a 6 MB total, and never leaves this browser profile.",
    chooseImages: "Choose images",
    removeImages: "Remove all",
    noCustomImages: "No custom images added",
    imageCount: "{count} local image(s)",
    interfaceTheme: "Extension theme",
    interfaceThemeDescription: "Changes the popup and this settings page only.",
    themeSystem: "System",
    themeLight: "Light",
    themeDark: "Dark",
    themeSolarized: "Solarized",
    themeForest: "Forest",
    sectionRules: "Advanced rules",
    sectionRulesDescription: "Manage site exceptions, blocked request domains, hidden elements, and HTTPS filter-list subscriptions.",
    siteExceptions: "Site exceptions",
    siteExceptionsDescription: "Protection stays off on these domains. Enter one domain per line, for example example.com.",
    blockedDomains: "Blocked domains",
    blockedDomainsDescription: "Always block requests to these domains. Up to 1,000 entries.",
    cosmeticRules: "Hidden page elements",
    cosmeticRulesDescription: "CSS selectors created by the element picker or entered manually. Invalid selectors are ignored.",
    filterSubscriptions: "Filter-list subscriptions",
    filterSubscriptionsDescription: "Add up to two direct HTTPS filter-list URLs. Unsafe allow, redirect, scriptlet, and unsupported rules are rejected.",
    saveRules: "Save rules",
    updateLists: "Update lists now",
    updated: "Updated {time}",
    updateFailed: "Update failed: {error}",
    ruleSummary: "{network} network · {cosmetic} page rules",
    sectionData: "Data and privacy",
    sectionDataDescription: "Review local storage behavior, create a backup, or restore default settings.",
    localOnly: "Local by design",
    localOnlyDescription: "Settings, tab analytics, and rule diagnostics stay on this Mac. Browser Monitor has no analytics server or account.",
    backup: "Backup and restore",
    backupDescription: "Export all extension settings and exceptions to a local JSON file, or restore a previous backup. Cookies and tab analytics are excluded; Chrome-account sync is not used.",
    exportSettings: "Export settings",
    importSettings: "Import settings",
    resetSettings: "Restore defaults",
    activityLauncherTitle: "Site activity · NEW",
    activityLauncherDescription: "Active time, reading and video",
    activityHint: "Open site activity analytics",
    feedbackButton: "Feedback",
    feedbackHint: "Suggest a tool or report a problem",
    sectionFeedback: "Feedback",
    sectionFeedbackDescription: "Suggest a new tool or report a problem. Requests are reviewed before they are submitted.",
    feedbackCardTitle: "Help improve Browser Monitor",
    feedbackCardDescription: "Open a short form with your email, request details, and an optional screenshot.",
    openFeedback: "Open feedback form",
    backupReady: "Settings backup downloaded.",
    importReady: "Settings restored. Open pages may need to be reloaded.",
    invalidBackup: "This backup file is invalid or unsupported.",
    resetConfirm: "Restore all protection settings to their defaults? Site exceptions and custom rules will be removed.",
    importConfirm: "Replace current protection settings and exceptions with this backup?",
    saved: "Saved",
    saving: "Saving…",
    error: "Could not save changes.",
    openSettings: "Open settings",
    collecting: "Collecting data…",
    analysisPaused: "Tab analysis is paused",
    tabsSummary: "{tabs} · {attention}",
    tabsCountOne: "1 tab",
    tabsCountMany: "{count} tabs",
    attentionOne: "1 needs attention",
    attentionMany: "{count} need attention",
    appConnected: "App connected",
    extensionOnly: "Extension only",
    currentSite: "Current site",
    checkingAddress: "Checking address…",
    excludeSite: "Exclude site",
    protectSite: "Protect site",
    reportSite: "Report a filter problem on this site",
    allowedHere: "Ads and trackers are allowed here",
    protectionActiveHere: "Ads and trackers are blocked on this site",
    pausedUntil: "Paused until {time}",
    pause10: "Pause 10 min",
    resume: "Resume",
    exceptions: "Exceptions",
    remove: "Remove",
    tabActivity: "Tab activity",
    tools: "Tools",
    statisticsButton: "Stats",
    statisticsHint: "Open blocking statistics",
    statisticsTitle: "Blocking activity",
    statisticsDescription: "A private, local view of Browser Monitor protection.",
    liveUpdates: "Live updates",
    blockedToday: "Blocked today",
    blockedSevenDays: "Last 7 days",
    rollingWindow: "Rolling local window",
    networkRequests: "Network",
    videoAndSponsors: "Video + sponsors",
    sevenDayActivity: "Seven-day activity",
    sevenDayActivityDescription: "Blocked requests and recognized video interruptions.",
    topBlockedSites: "Top sites",
    topBlockedSitesDescription: "Pages where protection was most active.",
    blockedResources: "Blocked resources",
    blockedResourcesDescription: "Domains and video categories stopped by protection.",
    noBlockingActivity: "No blocking activity yet.",
    noBlockedResources: "Blocked resources will appear here.",
    statisticsPrivacy: "Only seven days of compact counters are kept locally. Full page URLs are not stored; SponsorBlock results may cache a YouTube video ID for up to 12 hours.",
    clearStatistics: "Clear statistics",
    clearStatisticsConfirm: "Clear all locally stored blocking statistics?",
    statisticsBreakdown: "{network} network · {video} video · {sponsor} sponsors",
    waitingForBlocks: "Waiting for activity",
    cookies: "Cookies",
    blockElement: "Block",
    refresh: "Refresh",
    tabDetails: "Tab details",
    whyItMatters: "Why it matters",
    recommendation: "Recommendation",
    export: "Export",
    saveAs: "Save As",
    copy: "Copy",
    exportAllCookies: "Export all browser cookies",
    exportFormat: "Export format",
    noCookies: "No cookies found for this site.",
    cookieWarning: "Cookie files can grant account access. Keep exports private.",
    settingsHint: "All protection controls and explanations",
    openRegularPage: "Open a regular webpage to see its activity.",
    turnAnalysisOn: "Turn analysis on to monitor tab load.",
    untitled: "Untitled",
    noSignificantLoad: "No significant load sources detected",
    pauseTab: "Pause",
    resumeTab: "Resume",
    restoreTabActivity: "Restore normal tab activity",
    pauseTabActivity: "Pause media, animations, and background network activity",
    activeTab: "Active tab",
    backgroundTab: "Background tab",
    visibleTab: "Visible tab",
    noActionNeeded: "No action is needed right now.",
    metricLongFrames: "Long frames",
    metricBlocking: "Blocking",
    metricLayout: "Layout",
    metricResources: "Resources",
    metricTransferred: "Transferred",
    metricBackground: "Background",
    metricMedia: "Media",
    metricSample: "Sample",
    pauseThisTab: "Pause this tab",
    resumeNormalTab: "Resume normal tab activity",
    internalUnavailable: "Unavailable on Chrome internal pages",
    pictureInPictureActive: "Picture-in-Picture is active",
    noVideoFound: "No video found in the current tab",
    videoFoundOne: "1 video element found",
    videoFoundMany: "{count} video elements found",
    reloadAfterInstall: "Reload the page after installing the extension",
    openingPiP: "Opening Picture-in-Picture…",
    readingCookies: "Reading cookies locally…",
    preparingExport: "Preparing export…",
    preparingCopy: "Preparing a private copy…",
    cookiesCopied: "{count} cookies copied. Paste only into a trusted destination.",
    cookiesExported: "{count} cookies exported to {filename}",
    cookieExportFailed: "Cookie export failed",
    permissionRequired: "Permission was not granted. You can try again when you need this tool.",
    exportAllConfirm: "Export every browser cookie? This file may provide access to signed-in accounts. Store it securely and never share it.",
    filtersCount: "{network} + {cosmetic} filters",
    reasonLongBlocks: "Long main-thread blocks",
    reasonLayout: "Frequent style and layout recalculation",
    reasonNetwork: "High network resource volume",
    reasonBackground: "Activity continues in the background",
    reasonMedia: "Active media elements on the page",
    recommendationNormal: "This tab can remain open.",
    recommendationNoticeable: "Keep an eye on this tab, especially in the background.",
    recommendationHeavy: "Pause media or reload this tab.",
    recommendationCritical: "Close this tab if you do not need it right now.",
    severityNormal: "normal",
    severityNoticeable: "noticeable",
    severityHeavy: "heavy",
    severityCritical: "critical"
  },
  ru: {
    appName: "Browser Monitor",
    extensionEnabled: "Расширение включено",
    extensionPaused: "Browser Monitor приостановлен",
    settings: "Настройки",
    language: "Язык",
    english: "English",
    russian: "Русский",
    navAnalytics: "Аналитика",
    navGeneral: "Основные",
    navFilters: "Фильтры",
    navPageElements: "Элементы страниц",
    navLinkSafety: "Безопасность ссылок",
    navHistoryPrivacy: "Фильтр истории",
    navProtectionCenter: "Защита",
    navPrivacyTools: "Приватность",
    navProtection: "Защита",
    navComfort: "Комфорт",
    navAppearance: "Внешний вид",
    navRules: "Расширенные правила",
    navData: "Данные",
    navFeedback: "Обратная связь",
    heroEyebrow: "Защита браузера без лишнего шума",
    heroTitle: "Спокойнее страницы. Легче браузер.",
    heroDescription: "Блокируйте рекламу и слежение, убирайте помехи и находите причины нагрузки во вкладках. Все данные обрабатываются локально.",
    settingsTitle: "Настройки",
    settingsDescription: "Управляйте поведением расширения, инструментами страниц и локальными данными.",
    protectionOn: "Защита включена",
    protectionOff: "Защита выключена",
    activeRules: "активных сетевых правил",
    statusDescription: "Состояние основной защиты браузера",
    sectionGeneral: "Основные",
    sectionGeneralDescription: "Главные переключатели защиты и анализа вкладок.",
    sectionFilters: "Фильтры",
    sectionFiltersDescription: "Выберите сетевые и косметические списки, используемые расширением.",
    sectionProtectionCenter: "Защита",
    sectionProtectionCenterDescription: "Настройте, что Browser Monitor блокирует, скрывает или очищает при загрузке страниц.",
    filterListsGroup: "Сетевые фильтры и списки",
    filterListsGroupDescription: "Базовые правила блокировки рекламы, трекеров, майнеров и региональных рекламных ресурсов.",
    sectionPageElements: "Элементы страниц",
    sectionPageElementsDescription: "Настройте баннеры cookies, всплывающие окна, запросы, автовоспроизведение и плавающее видео.",
    pageCleanupGroup: "Очистка страниц",
    pageCleanupGroupDescription: "Дополнительные инструменты для оверлеев, запросов, видео-рекламы и рекламных интеграций.",
    sectionLinkSafety: "Безопасность ссылок",
    sectionLinkSafetyDescription: "Предупреждает перед переходом по ссылкам с фишинговыми или подозрительными признаками.",
    sectionHistoryPrivacy: "Фильтр истории",
    sectionHistoryPrivacyDescription: "Убирает выбранные домены из локальной истории Chrome и скрывает совпадающие поисковые подсказки на поддерживаемых поисковых страницах.",
    sectionPrivacyTools: "Приватность",
    sectionPrivacyToolsDescription: "Настройте предупреждения о ссылках, заблокированные переходы и локальную очистку истории в одном месте.",
    sectionAnalytics: "Аналитика вкладок",
    sectionAnalyticsDescription: "Посмотрите, какие открытые страницы создают нагрузку, почему это происходит и поможет ли пауза. Измерения остаются в этом профиле браузера.",
    refreshAnalytics: "Обновить анализ",
    analyticsUpdated: "Обновлено: {time}",
    openTabsStat: "Открытые вкладки",
    openTabsStatDescription: "Обычные веб-страницы, доступные для локального анализа.",
    attentionStat: "Требуют внимания",
    attentionStatDescription: "Тяжёлые и критические вкладки, которые стоит проверить.",
    activityHistory: "Недавняя активность",
    activityHistoryDescription: "Дневной пик нагрузки и число блокировок. В течение 90 дней хранятся только компактные итоги.",
    lastSevenDays: "7 дней",
    tabLoad: "Текущая нагрузка вкладок",
    tabLoadDescription: "Оценка учитывает блокировку основного потока, перерасчёт макета, сеть, медиа и фоновую активность.",
    noAnalyzedTabs: "Пока нет обычных веб-вкладок. Откройте сайт или включите анализ вкладок.",
    openTab: "Открыть вкладку",
    scoreLabel: "Оценка нагрузки",
    historyBlocked: "Заблокировано: {count}",
    historyScore: "пик {score}",
    sectionProtection: "Защита",
    sectionProtectionDescription: "Выберите, что Chrome будет блокировать до загрузки страницы. Декларативные правила работают внутри Chrome и не проверяют каждый запрос через JavaScript.",
    masterProtection: "Блокировать рекламу и трекеры",
    masterProtectionDescription: "Главный переключатель сетевой защиты и очистки страниц. Исключения для сайтов продолжают действовать.",
    tabAnalysis: "Анализировать активность вкладок",
    tabAnalysisDescription: "Измеряет долгие задачи, перерасчёт макета, загрузки, медиа и фоновую активность, чтобы объяснять нагрузку.",
    easyList: "Рекламные фильтры",
    easyListDescription: "EasyList блокирует баннеры, видеорекламу, рекламные серверы и навязчивые промоматериалы.",
    easyPrivacy: "Защита от слежения",
    easyPrivacyDescription: "EasyPrivacy блокирует аналитику и рекламные трекеры, которые связывают активность на разных сайтах.",
    crypto: "Защита от майнинга",
    cryptoDescription: "Останавливает известные скрипты, использующие процессор для майнинга без разрешения.",
    cosmetic: "Убирать пустые места рекламы",
    cosmeticDescription: "Скрывает рекламные контейнеры, оставшиеся после блокировки сетевых запросов.",
    russianFilters: "Фильтры русскоязычных страниц",
    russianFiltersDescription: "Добавляет сетевые и косметические правила RU AdList для рекламы на русскоязычных сайтах.",
    socialFilters: "Отслеживающие социальные кнопки",
    socialFiltersDescription: "Скрывает социальные виджеты, способные отслеживать посещения. Некоторые кнопки входа через соцсети тоже могут исчезнуть.",
    warningFilters: "Сообщения об отключении блокировщика",
    warningFiltersDescription: "Скрывает распространённые просьбы выключить защиту. Не обходит платный доступ и ограничения сайтов.",
    sectionComfort: "Комфорт",
    sectionComfortDescription: "Дополнительные инструменты против элементов, мешающих чтению. Они не работают, пока вы сами их не включите.",
    cookieBanners: "Баннеры согласия на cookies",
    cookieBannersDescription: "Скрывает поддерживаемые окна согласия, не принимая необязательные отслеживающие cookies от вашего имени.",
    newsletters: "Окна подписки на рассылку",
    newslettersDescription: "Убирает распространённые формы подписки, закрывающие содержимое страницы.",
    surveys: "Предложения пройти опрос",
    surveysDescription: "Скрывает распространённые окна опросов и обратной связи.",
    notificationPrompts: "Предложения включить уведомления",
    notificationPromptsDescription: "Скрывает собственные окна сайтов с просьбой включить push-уведомления. Системные запросы разрешений браузера не обходятся.",
    autoplay: "Нежелательное автовоспроизведение",
    autoplayDescription: "Приостанавливает автоматически запущенные аудио и видео до взаимодействия со страницей.",
    floatingVideo: "Плавающее и закреплённое видео",
    floatingVideoDescription: "Скрывает видео, которое следует за прокруткой. Обычные встроенные плееры остаются доступными.",
    videoAdProtection: "Реклама в видеоплеерах",
    videoAdProtectionDescription: "Блокирует известные ресурсы VAST, VPAID и IMA, а также распознанные элементы рекламы YouTube и Rutube. Обычное видео изменяется только при явном признаке рекламы.",
    sponsorSkipping: "Рекламные интеграции",
    sponsorSkippingDescription: "Пропускает отмеченные сообществом SponsorBlock фрагменты на YouTube. Для поиска отправляются только четыре символа SHA-256, а не полный адрес видео.",
    linkSafetyEnabled: "Предупреждения о подозрительных ссылках",
    linkSafetyEnabledDescription: "Открывает предупреждение Browser Monitor перед переходом на рискованные ссылки.",
    warnShorteners: "Сокращённые ссылки",
    warnShortenersDescription: "Предупреждает, когда назначение скрыто за популярным сервисом сокращения URL.",
    warnLookalikes: "Похожие домены",
    warnLookalikesDescription: "Предупреждает, когда адрес имитирует известный бренд, но настоящий домен другой.",
    warnPunycode: "Punycode и смешанные алфавиты",
    warnPunycodeDescription: "Предупреждает о доменах, которые могут скрывать похожие символы.",
    warnRedirects: "Вложенные редиректы",
    warnRedirectsDescription: "Предупреждает, когда параметры URL содержат другой адрес назначения.",
    warnUnknownFromSocial: "Ссылки из соцсетей",
    warnUnknownFromSocialDescription: "Усиливает предупреждения для рискованных ссылок из X, Reddit или Telegram Web.",
    linkSafetyAllowedDomains: "Разрешённые домены",
    linkSafetyAllowedDomainsDescription: "Не предупреждать для этих основных доменов. Один домен на строку.",
    linkSafetyBlockedDomains: "Заблокированные домены",
    linkSafetyBlockedDomainsDescription: "Всегда показывать предупреждение для этих основных доменов.",
    saveLinkSafety: "Сохранить безопасность ссылок",
    historyPrivacyEnabled: "Скрывать выбранные домены из истории",
    historyPrivacyEnabledDescription: "После разрешения пользователя Browser Monitor удаляет совпадающие записи локальной истории Chrome.",
    historyPrivacyDomains: "Домены для скрытия",
    historyPrivacyDomainsDescription: "Один основной домен на строку, например youtube.com. Подсказки с этими названиями скрываются на страницах Google, Yandex и Bing.",
    saveHistoryPrivacy: "Сохранить фильтр истории",
    purgeHistoryPrivacy: "Очистить совпадения сейчас",
    sectionAppearance: "Внешний вид",
    sectionAppearanceDescription: "Настройте замену рекламы изображениями и тему интерфейса.",
    imageSwap: "Замена рекламы изображениями",
    imageSwapDescription: "Заменяет до двух подходящих рекламных мест локальными изображениями. После двух замен сканирование прекращается.",
    imageCollection: "Коллекция изображений",
    landscape: "Пейзаж",
    ocean: "Океан",
    minimal: "Минимализм",
    custom: "Мои изображения",
    customImages: "Ваши локальные изображения",
    customImagesDescription: "Добавьте до девяти JPG, PNG, WebP, GIF или BMP: до 1 МБ на файл и до 6 МБ суммарно. Изображения не покидают этот профиль браузера.",
    chooseImages: "Выбрать изображения",
    removeImages: "Удалить все",
    noCustomImages: "Изображения ещё не добавлены",
    imageCount: "Локальных изображений: {count}",
    interfaceTheme: "Тема расширения",
    interfaceThemeDescription: "Изменяет только всплывающее окно и эту страницу настроек.",
    themeSystem: "Системная",
    themeLight: "Светлая",
    themeDark: "Тёмная",
    themeSolarized: "Solarized",
    themeForest: "Лесная",
    sectionRules: "Расширенные правила",
    sectionRulesDescription: "Управляйте исключениями сайтов, заблокированными доменами запросов, скрытыми элементами и HTTPS-подписками на списки фильтров.",
    siteExceptions: "Исключения для сайтов",
    siteExceptionsDescription: "На этих доменах защита выключена. Укажите по одному домену в строке, например example.com.",
    blockedDomains: "Блокируемые домены",
    blockedDomainsDescription: "Всегда блокировать запросы к этим доменам. До 1 000 записей.",
    cosmeticRules: "Скрытые элементы страниц",
    cosmeticRulesDescription: "CSS-селекторы, созданные инструментом выбора элемента или добавленные вручную. Ошибочные селекторы игнорируются.",
    filterSubscriptions: "Подписки на списки фильтров",
    filterSubscriptionsDescription: "Добавьте до двух прямых HTTPS-ссылок. Небезопасные разрешающие правила, redirect, scriptlet и неподдерживаемые конструкции отклоняются.",
    saveRules: "Сохранить правила",
    updateLists: "Обновить списки",
    updated: "Обновлено {time}",
    updateFailed: "Ошибка обновления: {error}",
    ruleSummary: "Сетевых: {network} · для страниц: {cosmetic}",
    sectionData: "Данные и приватность",
    sectionDataDescription: "Проверьте правила локального хранения, создайте резервную копию или верните настройки по умолчанию.",
    localOnly: "Только локально",
    localOnlyDescription: "Настройки, аналитика вкладок и диагностика правил остаются на этом Mac. У Browser Monitor нет сервера аналитики или учётной записи.",
    backup: "Резервная копия и восстановление",
    backupDescription: "Экспортируйте настройки и исключения в локальный JSON-файл или восстановите прежнюю копию. Cookies и аналитика вкладок не включаются; синхронизация через аккаунт Chrome не используется.",
    exportSettings: "Экспортировать настройки",
    importSettings: "Импортировать настройки",
    resetSettings: "Вернуть значения по умолчанию",
    activityLauncherTitle: "Аналитика посещений · NEW",
    activityLauncherDescription: "Активное время, чтение и видео",
    activityHint: "Открыть аналитику посещений",
    feedbackButton: "Связь",
    feedbackHint: "Предложить инструмент или сообщить об ошибке",
    sectionFeedback: "Обратная связь",
    sectionFeedbackDescription: "Предложите новый инструмент или сообщите об ошибке. Перед отправкой запрос можно проверить.",
    feedbackCardTitle: "Помогите улучшить Browser Monitor",
    feedbackCardDescription: "Откройте короткую форму с почтой, описанием запроса и необязательным скриншотом.",
    openFeedback: "Открыть форму",
    backupReady: "Резервная копия настроек сохранена.",
    importReady: "Настройки восстановлены. Открытые страницы может потребоваться обновить.",
    invalidBackup: "Файл резервной копии повреждён или не поддерживается.",
    resetConfirm: "Вернуть все настройки защиты по умолчанию? Исключения и пользовательские правила будут удалены.",
    importConfirm: "Заменить текущие настройки защиты и исключения данными из этой копии?",
    saved: "Сохранено",
    saving: "Сохранение…",
    error: "Не удалось сохранить изменения.",
    openSettings: "Открыть настройки",
    collecting: "Сбор данных…",
    analysisPaused: "Анализ вкладок приостановлен",
    tabsSummary: "{tabs} · {attention}",
    tabsCountOne: "1 вкладка",
    tabsCountMany: "Вкладок: {count}",
    attentionOne: "1 требует внимания",
    attentionMany: "Требуют внимания: {count}",
    appConnected: "Приложение подключено",
    extensionOnly: "Только расширение",
    currentSite: "Текущий сайт",
    checkingAddress: "Проверка адреса…",
    excludeSite: "Исключить сайт",
    protectSite: "Защитить сайт",
    reportSite: "Сообщить о проблеме фильтров на этом сайте",
    allowedHere: "Реклама и трекеры разрешены",
    protectionActiveHere: "Реклама и трекеры блокируются на этом сайте",
    pausedUntil: "Пауза до {time}",
    pause10: "Пауза 10 мин",
    resume: "Продолжить",
    exceptions: "Исключения",
    remove: "Удалить",
    tabActivity: "Активность вкладок",
    tools: "Инструменты",
    statisticsButton: "Статистика",
    statisticsHint: "Открыть статистику блокировок",
    statisticsTitle: "Активность защиты",
    statisticsDescription: "Приватная локальная статистика Browser Monitor.",
    liveUpdates: "Обновляется в реальном времени",
    blockedToday: "Заблокировано сегодня",
    blockedSevenDays: "За последние 7 дней",
    rollingWindow: "Скользящий локальный период",
    networkRequests: "Сеть",
    videoAndSponsors: "Видео и интеграции",
    sevenDayActivity: "Активность за семь дней",
    sevenDayActivityDescription: "Заблокированные запросы и распознанные рекламные фрагменты.",
    topBlockedSites: "Топ сайтов",
    topBlockedSitesDescription: "Страницы, где защита срабатывала чаще всего.",
    blockedResources: "Заблокированные ресурсы",
    blockedResourcesDescription: "Домены и категории видеорекламы, остановленные защитой.",
    noBlockingActivity: "Блокировок пока не было.",
    noBlockedResources: "Заблокированные ресурсы появятся здесь.",
    statisticsPrivacy: "Локально хранятся только компактные счётчики за семь дней. Полные адреса страниц не сохраняются; результат SponsorBlock может хранить ID видео YouTube до 12 часов.",
    clearStatistics: "Очистить статистику",
    clearStatisticsConfirm: "Удалить всю локальную статистику блокировок?",
    statisticsBreakdown: "Сеть: {network} · видео: {video} · интеграции: {sponsor}",
    waitingForBlocks: "Ожидание активности",
    cookies: "Cookies",
    blockElement: "Скрыть",
    refresh: "Обновить",
    tabDetails: "Сведения о вкладке",
    whyItMatters: "Почему это важно",
    recommendation: "Рекомендация",
    export: "Экспорт",
    saveAs: "Сохранить как",
    copy: "Копировать",
    exportAllCookies: "Экспортировать все cookies браузера",
    exportFormat: "Формат экспорта",
    noCookies: "Cookies для этого сайта не найдены.",
    cookieWarning: "Файл cookies может дать доступ к аккаунтам. Храните его в безопасном месте.",
    settingsHint: "Все функции защиты и понятные объяснения",
    openRegularPage: "Откройте обычную веб-страницу, чтобы увидеть её активность.",
    turnAnalysisOn: "Включите анализ, чтобы отслеживать нагрузку вкладок.",
    untitled: "Без названия",
    noSignificantLoad: "Заметных источников нагрузки не обнаружено",
    pauseTab: "Пауза",
    resumeTab: "Вернуть",
    restoreTabActivity: "Вернуть обычную активность вкладки",
    pauseTabActivity: "Приостановить медиа, анимации и фоновую сеть",
    activeTab: "Активная вкладка",
    backgroundTab: "Фоновая вкладка",
    visibleTab: "Видимая вкладка",
    noActionNeeded: "Сейчас никаких действий не требуется.",
    metricLongFrames: "Долгие кадры",
    metricBlocking: "Блокировка",
    metricLayout: "Макет",
    metricResources: "Ресурсы",
    metricTransferred: "Загружено",
    metricBackground: "Фон",
    metricMedia: "Медиа",
    metricSample: "Период",
    pauseThisTab: "Приостановить эту вкладку",
    resumeNormalTab: "Вернуть обычную работу вкладки",
    internalUnavailable: "Недоступно на служебных страницах Chrome",
    pictureInPictureActive: "Режим «картинка в картинке» активен",
    noVideoFound: "В текущей вкладке видео не найдено",
    videoFoundOne: "Найден 1 видеоэлемент",
    videoFoundMany: "Найдено видеоэлементов: {count}",
    reloadAfterInstall: "Обновите страницу после установки расширения",
    openingPiP: "Открытие режима «картинка в картинке»…",
    readingCookies: "Локальное чтение cookies…",
    preparingExport: "Подготовка экспорта…",
    preparingCopy: "Подготовка приватной копии…",
    cookiesCopied: "Скопировано cookies: {count}. Вставляйте только в надёжное место.",
    cookiesExported: "Экспортировано cookies: {count}. Файл: {filename}",
    cookieExportFailed: "Не удалось экспортировать cookies",
    permissionRequired: "Доступ не предоставлен. При необходимости можно повторить попытку.",
    exportAllConfirm: "Экспортировать все cookies браузера? Этот файл может дать доступ к авторизованным аккаунтам. Храните его безопасно и никому не передавайте.",
    filtersCount: "{network} + {cosmetic} фильтров",
    reasonLongBlocks: "Долгие блокировки основного потока",
    reasonLayout: "Частый перерасчёт стилей и макета",
    reasonNetwork: "Большой объём сетевых ресурсов",
    reasonBackground: "Активность продолжается в фоне",
    reasonMedia: "На странице работают медиаэлементы",
    recommendationNormal: "Эту вкладку можно оставить открытой.",
    recommendationNoticeable: "Следите за этой вкладкой, особенно в фоновом режиме.",
    recommendationHeavy: "Приостановите медиа или обновите вкладку.",
    recommendationCritical: "Закройте вкладку, если она сейчас не нужна.",
    severityNormal: "норма",
    severityNoticeable: "заметная",
    severityHeavy: "высокая",
    severityCritical: "критическая"
  }
};

export function normalizeLanguage(value) {
  return SUPPORTED_LANGUAGES.includes(value) ? value : "en";
}

export function browserLanguage() {
  return normalizeLanguage((navigator.language || "en").toLowerCase().startsWith("ru") ? "ru" : "en");
}

export function translate(language, key, values = {}) {
  const template = messages[normalizeLanguage(language)][key] ?? messages.en[key] ?? key;
  return Object.entries(values).reduce(
    (result, [name, value]) => result.replaceAll(`{${name}}`, String(value)),
    template
  );
}

export function localizeDocument(language, root = document) {
  const normalized = normalizeLanguage(language);
  document.documentElement.lang = normalized;
  for (const element of root.querySelectorAll("[data-i18n]")) {
    element.textContent = translate(normalized, element.dataset.i18n);
  }
  for (const element of root.querySelectorAll("[data-i18n-title]")) {
    element.title = translate(normalized, element.dataset.i18nTitle);
  }
  for (const element of root.querySelectorAll("[data-i18n-aria]")) {
    element.setAttribute("aria-label", translate(normalized, element.dataset.i18nAria));
  }
  return normalized;
}
